#!/bin/bash
#
# LEAD GENERATION & BUSINESS DEVELOPMENT - QUICK START
# Leverages your full infrastructure to win clients and opportunities
#
# Author: Simon Renauld
# Created: November 4, 2025

set -e

echo "=================================================================="
echo "🚀 LEAD GENERATION ENGINE - QUICK START"
echo "=================================================================="
echo ""
echo "Your Infrastructure Assets:"
echo "  ✓ Portfolio: https://www.simondatalab.de"
echo "  ✓ Training: https://moodle.simondatalab.de"
echo "  ✓ Company Page: https://linkedin.com/company/105307318"
echo "  ✓ AI Homelab: ProxmoxMCP + VM 159 agents"
echo "  ✓ Analytics: Grafana + Prometheus monitoring"
echo ""

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo "=================================================================="
echo "STEP 1: Generate Infrastructure Showcase"
echo "=================================================================="
echo ""

if [ ! -f "outputs/showcase/infrastructure-showcase.html" ]; then
    echo "Generating showcase page..."
    python3 infrastructure_showcase.py
else
    echo "✓ Showcase already generated"
fi

echo ""
echo "View your showcase:"
echo "  file://$SCRIPT_DIR/outputs/showcase/infrastructure-showcase.html"
echo ""

echo "=================================================================="
echo "STEP 2: Find High-Value Leads"
echo "=================================================================="
echo ""
echo "Target roles to search:"
echo "  1. Head of Data / VP Data"
echo "  2. CTO / VP Engineering"
echo "  3. Director of Analytics"
echo "  4. ML Engineering Lead"
echo ""
echo "Example searches:"
echo "  python3 lead_generation_engine.py find 'Head of Data' 'Vietnam'"
echo "  python3 lead_generation_engine.py find 'CTO Healthcare' 'Singapore'"
echo ""

read -p "Search for leads now? (y/n): " DO_SEARCH

if [ "$DO_SEARCH" = "y" ]; then
    read -p "Enter job title (e.g., 'Head of Data'): " JOB_TITLE
    read -p "Enter location (e.g., 'Vietnam'): " LOCATION
    
    python3 lead_generation_engine.py find "$JOB_TITLE" "$LOCATION"
    echo ""
    echo "✓ Leads saved to outputs/leads/"
fi

echo ""
echo "=================================================================="
echo "STEP 3: View Lead Pipeline"
echo "=================================================================="
echo ""

if [ -d "outputs/leads" ] && [ "$(ls -A outputs/leads)" ]; then
    python3 lead_generation_engine.py pipeline
else
    echo "No leads found yet. Run searches first."
fi

echo ""
echo "=================================================================="
echo "RECOMMENDED ACTIONS (Do These Today)"
echo "=================================================================="
echo ""
echo "1. LINKEDIN OPTIMIZATION (30 minutes)"
echo "   □ Update LinkedIn headline with key metrics"
echo "   □ Add portfolio link to featured section"
echo "   □ Post infrastructure showcase"
echo ""
echo "2. OUTBOUND OUTREACH (1 hour/day)"
echo "   □ Connect with 5-10 target prospects daily"
echo "   □ Personalize messages using generated templates"
echo "   □ Share relevant case studies"
echo ""
echo "3. CONTENT MARKETING (2 hours/week)"
echo "   □ Post on company page (Mon/Wed/Fri)"
echo "   □ Share technical insights (healthcare, MLOps)"
echo "   □ Engage with prospect posts"
echo ""
echo "4. PORTFOLIO UPDATES (2 hours/week)"
echo "   □ Add new case studies"
echo "   □ Update metrics (courses, students)"
echo "   □ Add infrastructure diagrams"
echo ""
echo "5. DIRECT OUTREACH (Ongoing)"
echo "   □ Email 10 prospects/week"
echo "   □ Follow up after 1 week"
echo "   □ Offer 15-min discovery calls"
echo ""

echo "=================================================================="
echo "QUICK WINS (Next 7 Days)"
echo "=================================================================="
echo ""
echo "Day 1 (TODAY):"
echo "  □ Generate infrastructure showcase ✓"
echo "  □ Find 20 high-value leads"
echo "  □ Update LinkedIn profile"
echo ""
echo "Day 2:"
echo "  □ Send 10 connection requests (personalized)"
echo "  □ Post infrastructure showcase on LinkedIn"
echo "  □ Email 5 prospects"
echo ""
echo "Day 3:"
echo "  □ Engage with 10 prospect posts (comment)"
echo "  □ Send 10 more connection requests"
echo "  □ Follow up on Day 2 emails"
echo ""
echo "Day 4:"
echo "  □ Post healthcare analytics case study"
echo "  □ Send InMail to 5 high-fit leads"
echo "  □ Update portfolio with new metrics"
echo ""
echo "Day 5:"
echo "  □ Review responses, schedule calls"
echo "  □ Send 10 connection requests"
echo "  □ Post AI homelab update"
echo ""
echo "Day 6-7:"
echo "  □ Conduct discovery calls"
echo "  □ Prepare proposals for interested leads"
echo "  □ Plan next week's content"
echo ""

echo "=================================================================="
echo "AUTOMATED WORKFLOWS"
echo "=================================================================="
echo ""
echo "Setup automation:"
echo ""
echo "1. Company Page Posting:"
echo "   crontab -e"
echo "   # Add:"
echo "   0 10 * * 1-5 cd $SCRIPT_DIR && ./venv/bin/python orchestrator.py daily"
echo ""
echo "2. Lead Tracking:"
echo "   # Review pipeline weekly"
echo "   0 9 * * 1 cd $SCRIPT_DIR && ./venv/bin/python lead_generation_engine.py pipeline"
echo ""
echo "3. Analytics Monitoring:"
echo "   # Track LinkedIn growth"
echo "   0 8 * * * cd $SCRIPT_DIR && ./venv/bin/python analytics_tracker.py scrape-page"
echo ""

echo "=================================================================="
echo "OUTREACH TEMPLATES"
echo "=================================================================="
echo ""
echo "Generated templates available in outputs/outreach/"
echo ""
echo "To generate personalized outreach:"
echo "  python3 lead_generation_engine.py outreach <lead_id> inmail"
echo "  python3 lead_generation_engine.py outreach <lead_id> email"
echo ""

echo "=================================================================="
echo "SHOWCASE YOUR INFRASTRUCTURE"
echo "=================================================================="
echo ""
echo "Share these links with prospects:"
echo ""
echo "  Portfolio:"
echo "    https://www.simondatalab.de"
echo ""
echo "  Training Platform:"
echo "    https://moodle.simondatalab.de"
echo ""
echo "  Infrastructure Showcase:"
echo "    file://$SCRIPT_DIR/outputs/showcase/infrastructure-showcase.html"
echo "    (Upload to portfolio or share via screen share)"
echo ""
echo "  Company Page:"
echo "    https://www.linkedin.com/company/105307318"
echo ""

echo "=================================================================="
echo "EXPECTED RESULTS (30 Days)"
echo "=================================================================="
echo ""
echo "Assuming:"
echo "  - 10 connection requests/day = 300/month"
echo "  - 5% acceptance rate = 15 new connections"
echo "  - 20% response rate = 3 conversations"
echo "  - 33% conversion to call = 1 opportunity/month"
echo ""
echo "Reality check:"
echo "  - Month 1: 1-2 qualified leads"
echo "  - Month 2: 3-5 opportunities"
echo "  - Month 3: 1-2 clients/contracts"
echo ""

echo "=================================================================="
echo "KEY SUCCESS METRICS"
echo "=================================================================="
echo ""
echo "Track these weekly:"
echo "  □ LinkedIn connections added"
echo "  □ Messages sent / responses received"
echo "  □ Discovery calls scheduled"
echo "  □ Proposals sent"
echo "  □ Contracts signed"
echo "  □ Portfolio views (simondatalab.de analytics)"
echo "  □ Moodle enrollments (social proof)"
echo ""

echo "=================================================================="
echo "✅ SETUP COMPLETE - YOU'RE READY TO GENERATE LEADS!"
echo "=================================================================="
echo ""
echo "What to do RIGHT NOW:"
echo ""
echo "1. View your infrastructure showcase:"
echo "   xdg-open $SCRIPT_DIR/outputs/showcase/infrastructure-showcase.html"
echo ""
echo "2. Find your first leads:"
echo "   python3 lead_generation_engine.py find 'Head of Data' 'Vietnam'"
echo ""
echo "3. Generate outreach messages:"
echo "   python3 lead_generation_engine.py pipeline"
echo "   # Note the lead IDs"
echo "   python3 lead_generation_engine.py outreach <lead_id> inmail"
echo ""
echo "4. Post your showcase on LinkedIn:"
echo "   python3 company_page_automation.py post 'Check out our production infrastructure...' --link https://www.simondatalab.de"
echo ""
echo "Good luck! 🚀"
echo ""
