#!/bin/bash
#
# IMMEDIATE FIX COMMANDS for Prometheus Targets
# Copy and paste these commands one by one
#

echo "🔧 PROMETHEUS TARGETS FIX - MANUAL EXECUTION"
echo "============================================="
echo ""
echo "Current Status:"
echo "✅ proxmox-host (136.243.155.166:9100) - UP"
echo "✅ vm159-node (10.0.0.110:9100) - UP"
echo "❌ pve_exporter (127.0.0.1:9221) - DOWN"
echo "❌ vm159-cadvisor (10.0.0.110:8080) - DOWN"
echo ""

echo "STEP 1: Fix PVE Exporter"
echo "========================"
echo "Run these commands in sequence:"
echo ""
echo "# Connect to Proxmox host"
echo "ssh root@136.243.155.166"
echo ""
echo "# Install PVE exporter"
echo "pip3 install prometheus-pve-exporter"
echo ""
echo "# Create config file"
echo "cat > /etc/pve_exporter.yml <<'EOF'"
echo "default:"
echo "    user: root@pam"
echo "    verify_ssl: false"
echo "EOF"
echo ""
echo "# Create systemd service"
echo "cat > /etc/systemd/system/pve_exporter.service <<'EOF'"
echo "[Unit]"
echo "Description=Proxmox VE Exporter for Prometheus"
echo "After=network.target"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=root"
echo "ExecStart=/usr/local/bin/pve_exporter --address 127.0.0.1:9221 --config-file /etc/pve_exporter.yml"
echo "Restart=on-failure"
echo "RestartSec=5s"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""
echo "# Start the service"
echo "systemctl daemon-reload"
echo "systemctl enable pve_exporter"
echo "systemctl start pve_exporter"
echo ""
echo "# Test the service"
echo "curl http://127.0.0.1:9221/metrics | head -5"
echo ""
echo "# Exit SSH"
echo "exit"
echo ""

echo "STEP 2: Fix cAdvisor"
echo "===================="
echo "Run these commands in sequence:"
echo ""
echo "# Connect to VM159"
echo "ssh root@10.0.0.110"
echo ""
echo "# Remove old cAdvisor if exists"
echo "docker stop cadvisor 2>/dev/null || true"
echo "docker rm cadvisor 2>/dev/null || true"
echo ""
echo "# Start new cAdvisor container"
echo "docker run -d \\"
echo "  --name=cadvisor \\"
echo "  --restart=unless-stopped \\"
echo "  --volume=/:/rootfs:ro \\"
echo "  --volume=/var/run:/var/run:ro \\"
echo "  --volume=/sys:/sys:ro \\"
echo "  --volume=/var/lib/docker/:/var/lib/docker:ro \\"
echo "  --volume=/dev/disk/:/dev/disk:ro \\"
echo "  --publish=8080:8080 \\"
echo "  --privileged \\"
echo "  --device=/dev/kmsg \\"
echo "  gcr.io/cadvisor/cadvisor:latest"
echo ""
echo "# Verify container is running"
echo "sleep 5"
echo "docker ps | grep cadvisor"
echo "curl http://localhost:8080/metrics | head -5"
echo ""
echo "# Exit SSH"
echo "exit"
echo ""

echo "STEP 3: Verification"
echo "===================="
echo "After completing both steps:"
echo "1. Wait 2 minutes for Prometheus to detect changes"
echo "2. Refresh: https://prometheus.simondatalab.de/targets"
echo "3. All targets should show as UP:"
echo "   ✅ proxmox-host (136.243.155.166:9100)"
echo "   ✅ pve_exporter (127.0.0.1:9221)"
echo "   ✅ vm159-node (10.0.0.110:9100)"
echo "   ✅ vm159-cadvisor (10.0.0.110:8080)"
echo ""

echo "TROUBLESHOOTING"
echo "==============="
echo "If PVE exporter fails:"
echo "- Check logs: journalctl -u pve_exporter -n 20"
echo "- Restart: systemctl restart pve_exporter"
echo ""
echo "If cAdvisor fails:"
echo "- Check logs: docker logs cadvisor"
echo "- Restart: docker restart cadvisor"
echo ""

echo "SUCCESS INDICATORS"
echo "=================="
echo "✅ All 4 targets showing UP in Prometheus"
echo "✅ No 'connection refused' errors"
echo "✅ Metrics flowing to Grafana dashboards"
echo ""