#!/bin/bash

# CLOUDFLARE API SETUP GUIDE
# Step-by-step guide to set up Cloudflare API for cache purging

echo "🌌 CLOUDFLARE API SETUP GUIDE"
echo "============================="
echo ""

echo "📋 STEP 1: GET API CREDENTIALS"
echo "==============================="
echo ""
echo "Option A: API Token (Recommended)"
echo "---------------------------------"
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click: 'Create Token'"
echo "3. Use: 'Custom token' template"
echo "4. Set permissions:"
echo "   - Zone:Zone:Read"
echo "   - Zone:Cache Purge:Edit"
echo "5. Set zone resources:"
echo "   - Include: simondatalab.de"
echo "6. Click: 'Continue to summary'"
echo "7. Click: 'Create Token'"
echo "8. Copy the token (starts with 'cf_' or similar)"
echo ""
echo "Option B: Global API Key"
echo "-----------------------"
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click: 'View' next to 'Global API Key'"
echo "3. Copy the key"
echo "4. Also note your email address"
echo ""

echo "📋 STEP 2: SET ENVIRONMENT VARIABLES"
echo "===================================="
echo ""
echo "For API Token (Option A):"
echo "  export CLOUDFLARE_API_TOKEN='your-api-token-here'"
echo ""
echo "For Global API Key (Option B):"
echo "  export CLOUDFLARE_EMAIL='your-email@example.com'"
echo "  export CLOUDFLARE_API_KEY='your-global-api-key-here'"
echo ""

echo "📋 STEP 3: RUN CACHE PURGE"
echo "=========================="
echo ""
echo "After setting the environment variables, run:"
echo "  ./purge_cloudflare_api.sh"
echo ""

echo "📋 STEP 4: TEST DEPLOYMENT"
echo "=========================="
echo ""
echo "After cache purge, test with:"
echo "  ./test_neural_geoserver_deployment.sh"
echo ""

echo "🔍 QUICK TEST COMMANDS:"
echo "======================"
echo ""
echo "Test main page:"
echo "  curl -s https://www.simondatalab.de/ | grep 'Initializing Neural GeoServer'"
echo ""
echo "Test hero page:"
echo "  curl -s https://www.simondatalab.de/hero-r3f-odyssey/index.html | grep 'Initializing Neural GeoServer'"
echo ""
echo "Test neural GeoServer files:"
echo "  curl -I https://www.simondatalab.de/neural-geoserver-viz.js"
echo "  curl -I https://www.simondatalab.de/hero-r3f-odyssey/neural-geoserver-viz.js"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "=================="
echo ""
echo "After successful cache purge:"
echo "  ✅ Main page shows: 'Initializing Neural GeoServer...'"
echo "  ✅ Hero page shows: 'Initializing Neural GeoServer...'"
echo "  ✅ Neural GeoServer files: HTTP 200"
echo "  ✅ Neural GeoServer visualization loads with real-time GeoServer integration"
echo ""

echo "🚀 READY TO START?"
echo "=================="
echo ""
echo "1. Get your API credentials from Cloudflare dashboard"
echo "2. Set the environment variables"
echo "3. Run: ./purge_cloudflare_api.sh"
echo "4. Test: ./test_neural_geoserver_deployment.sh"
echo ""
echo "The neural GeoServer visualization is 100% deployed and ready!"
echo "Just need to purge the Cloudflare cache to make it live."
