#!/bin/bash

# CLOUDFLARE API SSL FIX SETUP
# Quick setup and execution of SSL fix using your API access

echo "🔐 CLOUDFLARE API SSL FIX SETUP"
echo "==============================="
echo ""

echo "🔍 YOUR CLOUDFLARE CONFIGURATION:"
echo "================================="
echo "✅ Domain: simondatalab.de"
echo "✅ API Access: Zone.DNS Settings, Zone.Cache Purge, Zone.Firewall Services"
echo "✅ Email: sn.renauld@gmail.com"
echo "✅ Affected Services: moodle, grafana, jellyfin, nextcloud"
echo "✅ Origin IP: 136.243.155.166"
echo ""

echo "🚨 ISSUE: Error code 526 - Invalid SSL certificate"
echo "📅 Moodle was working yesterday (temporary issue)"
echo ""

echo "🛠️  QUICK FIX OPTIONS:"
echo "====================="
echo ""

echo "OPTION 1: Use API Token (Recommended)"
echo "------------------------------------"
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click 'Create Token'"
echo "3. Use 'Custom token' template"
echo "4. Set permissions:"
echo "   - Zone:Zone:Read"
echo "   - Zone:Zone Settings:Edit"
echo "5. Set zone resources:"
echo "   - Include: simondatalab.de"
echo "6. Copy the token and run:"
echo "   export CLOUDFLARE_API_TOKEN='your-token'"
echo "   ./fix_cloudflare_api_ssl.sh"
echo ""

echo "OPTION 2: Use Global API Key"
echo "---------------------------"
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click 'View' next to 'Global API Key'"
echo "3. Copy the key and run:"
echo "   export CLOUDFLARE_EMAIL='sn.renauld@gmail.com'"
echo "   export CLOUDFLARE_API_KEY='your-global-key'"
echo "   ./fix_cloudflare_api_ssl.sh"
echo ""

echo "OPTION 3: Manual Fix (If API doesn't work)"
echo "------------------------------------------"
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Select: simondatalab.de"
echo "3. Go to: SSL/TLS > Overview"
echo "4. Change SSL mode from 'Flexible' to 'Full'"
echo "5. Wait 2-3 minutes"
echo "6. Test services"
echo ""

echo "🧪 TESTING COMMANDS:"
echo "==================="
echo ""
echo "Test current SSL status:"
echo "  curl -I https://moodle.simondatalab.de/"
echo "  curl -I https://grafana.simondatalab.de/"
echo "  curl -I https://jellyfin.simondatalab.de/"
echo "  curl -I https://nextcloud.simondatalab.de/"
echo ""

echo "Test SSL certificate:"
echo "  openssl s_client -connect moodle.simondatalab.de:443 -servername moodle.simondatalab.de"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "=================="
echo ""
echo "After fixing SSL mode:"
echo "✅ All services return HTTP 200 (instead of 526)"
echo "✅ SSL certificates work correctly"
echo "✅ Cloudflare can connect to origin servers"
echo "✅ Services accessible via HTTPS"
echo ""

echo "🚨 COMMON ISSUES:"
echo "================="
echo ""
echo "1. SSL Mode 'Flexible':"
echo "   - Cloudflare expects HTTP from origin"
echo "   - But origin server (136.243.155.166) is HTTPS"
echo "   - Solution: Change to 'Full' mode"
echo ""
echo "2. Origin Server SSL Issues:"
echo "   - SSL certificate expired"
echo "   - SSL configuration changed"
echo "   - Solution: Check origin server SSL"
echo ""

echo "📞 IMMEDIATE ACTION:"
echo "==================="
echo ""
echo "Since Moodle was working yesterday, this is likely:"
echo "1. SSL mode changed to 'Flexible'"
echo "2. Temporary SSL certificate issue"
echo "3. Origin server SSL configuration changed"
echo ""
echo "Quick fix: Change Cloudflare SSL mode to 'Full'"
echo ""
echo "🔄 To run the API fix:"
echo "  ./fix_cloudflare_api_ssl.sh"
echo ""
echo "🔄 To run this setup again:"
echo "  ./cloudflare_ssl_setup.sh"
