#!/bin/bash

# Comprehensive CSP Fix Script for simondatalab.de
# This script fixes Content Security Policy violations by removing conflicting hashes

echo "🔧 Comprehensive CSP Fix Script"
echo "==============================="

# Configuration
JUMP_HOST="root@136.243.155.166:2222"
CT_ID="150"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

echo "1. Backing up current files..."
ssh -p 2222 root@136.243.155.166 "pct exec $CT_ID -- cp -r /var/www/html/creative_overhaul /var/www/html/creative_overhaul.backup.$(date +%Y%m%d_%H%M%S)"

echo ""
echo "2. Removing all CSP meta tags..."
ssh -p 2222 root@136.243.155.166 "pct exec $CT_ID -- find /var/www/html -name '*.html' -exec sed -i '/meta.*http-equiv.*Content-Security-Policy/d' {} \;"

echo ""
echo "3. Adding simplified CSP meta tag..."
# Create a simplified CSP meta tag
SIMPLIFIED_CSP='<meta http-equiv="Content-Security-Policy" content="default-src '\''self'\''; script-src '\''self'\'' '\''unsafe-inline'\'' '\''unsafe-eval'\'' https://cdnjs.cloudflare.com https://d3js.org https://static.cloudflareinsights.com; style-src '\''self'\'' '\''unsafe-inline'\'' https://cdnjs.cloudflare.com; img-src '\''self'\'' data: https:; font-src '\''self'\'' https://cdnjs.cloudflare.com; connect-src '\''self'\'' https:; frame-ancestors '\''self'\'';">'

# Add the simplified CSP meta tag to the head section
ssh -p 2222 root@136.243.155.166 "pct exec $CT_ID -- sed -i '/<head>/a\\$SIMPLIFIED_CSP' /var/www/html/creative_overhaul/index.html"

echo ""
echo "4. Testing the fix..."
sleep 5

# Test if CSP violations are resolved
CSP_CHECK=$(curl -s --max-time 10 https://www.simondatalab.de/ | grep -i "content-security-policy" | head -1)

if [ -n "$CSP_CHECK" ]; then
    echo "Current CSP: $CSP_CHECK"
    
    # Check if it contains problematic hashes
    if [[ "$CSP_CHECK" == *"sha384-"* ]]; then
        print_warning "CSP still contains problematic hashes"
        echo "💡 The CSP might be cached or dynamically generated"
    else
        print_status "CSP policy looks good - no problematic hashes found"
    fi
else
    print_status "No CSP meta tag found - this should resolve violations"
fi

echo ""
echo "5. Additional cleanup..."

# Remove any remaining CSP-related meta tags
ssh -p 2222 root@136.243.155.166 "pct exec $CT_ID -- find /var/www/html -name '*.html' -exec sed -i '/report-uri\|report-to\|csp-endpoint/d' {} \;"

echo ""
echo "6. Final verification..."
sleep 5

# Final test
FINAL_CSP=$(curl -s --max-time 10 https://www.simondatalab.de/ | grep -i "content-security-policy" | head -1)

if [ -n "$FINAL_CSP" ]; then
    echo "Final CSP: $FINAL_CSP"
    
    if [[ "$FINAL_CSP" == *"sha384-"* ]]; then
        print_error "CSP still contains problematic hashes"
        echo ""
        echo "🔧 Manual steps needed:"
        echo "   1. Check if CSP is being generated by JavaScript"
        echo "   2. Clear Cloudflare cache completely"
        echo "   3. Check for other sources of CSP policy"
    else
        print_status "CSP policy is now clean!"
    fi
else
    print_status "No CSP meta tag found - violations should be resolved"
fi

echo ""
echo "📋 Summary:"
echo "   - Removed problematic CSP meta tags with hash values"
echo "   - Added simplified CSP policy allowing inline scripts"
echo "   - Cleaned up CSP-related directives"
echo ""
echo "🌐 Test your website: https://www.simondatalab.de/"
echo "   Check browser console for CSP violations"

