#!/bin/bash

echo "📺 Complete Jellyfin Live TV Setup"
echo "=================================="
echo ""
echo "🎯 You want BOTH:"
echo "1. TV channels to watch (M3U tuners)"
echo "2. iptv-org EPG program guide"
echo ""
echo "✅ CORRECT CONFIGURATION:"
echo "========================"
echo ""
echo "Tuner Devices (for watching channels):"
echo "  M3U /config/samsung_tv_plus.m3u"
echo "  M3U /config/plex_live.m3u"
echo "  M3U /config/tubi_tv.m3u"
echo ""
echo "TV Guide Data Providers (for program guide):"
echo "  XMLTV /config/epg_us.xml"
echo ""
echo "🔧 Setup Steps:"
echo "==============="
echo ""
echo "Step 1: Configure Tuner Devices"
echo "-------------------------------"
echo "1. Go to Admin Panel → Live TV"
echo "2. Click '+' next to 'Tuner Devices'"
echo "3. Select 'M3U Tuner'"
echo "4. File or URL: /config/samsung_tv_plus.m3u"
echo "5. Click 'Save'"
echo "6. Repeat for /config/plex_live.m3u and /config/tubi_tv.m3u"
echo ""
echo "Step 2: Configure TV Guide Data Provider"
echo "----------------------------------------"
echo "1. Click '+' next to 'TV Guide Data Providers'"
echo "2. Select 'XMLTV'"
echo "3. File or URL: /config/epg_us.xml"
echo "4. Click 'Save'"
echo ""
echo "Step 3: Refresh Guide Data"
echo "--------------------------"
echo "1. Click 'Refresh Guide Data' button"
echo "2. Wait for guide to populate"
echo ""
echo "Step 4: Access Live TV"
echo "---------------------"
echo "1. Go to main Jellyfin menu"
echo "2. Click 'Live TV'"
echo "3. Browse and watch channels with program guide!"
echo ""
echo "🎯 What You'll Get:"
echo "=================="
echo "✅ Free TV channels from Samsung TV Plus"
echo "✅ Free TV channels from Plex Live"
echo "✅ Free TV channels from Tubi TV"
echo "✅ Program guide with show schedules"
echo "✅ Channel information and descriptions"
echo "✅ Complete Live TV experience"
echo ""
echo "📺 Channel Sources:"
echo "=================="
echo "• Samsung TV Plus: Free Samsung channels"
echo "• Plex Live: Free Plex channels"
echo "• Tubi TV: Free Tubi channels"
echo "• iptv-org EPG: Program guide data"
echo ""
echo "🌐 Access:"
echo "========="
echo "URL: http://136.243.155.166:8096/web/"
echo "User: simonadmin"
echo ""
echo "🎉 Complete Live TV setup with channels + program guide!"
