#!/bin/bash

echo "🔧 Jellyfin Live TV Configuration Fix"
echo "======================================"
echo ""
echo "❌ Current Problem:"
echo "  Tuner Devices shows: M3U /config/epg_us.xml"
echo "  This is WRONG - epg_us.xml is an EPG file, not a tuner!"
echo ""
echo "✅ Correct Configuration Should Be:"
echo ""
echo "Tuner Devices:"
echo "  M3U /config/samsung_tv_plus.m3u"
echo "  M3U /config/plex_live.m3u"
echo "  M3U /config/tubi_tv.m3u"
echo ""
echo "TV Guide Data Providers:"
echo "  XMLTV /config/epg_us.xml"
echo ""
echo "🔧 How to Fix:"
echo "  1. Go to Admin Panel → Live TV"
echo "  2. Find the tuner with '/config/epg_us.xml'"
echo "  3. Click the 'X' or 'Delete' button to remove it"
echo "  4. Click '+' next to 'Tuner Devices'"
echo "  5. Select 'M3U Tuner'"
echo "  6. Use file: /config/samsung_tv_plus.m3u"
echo "  7. Click 'Save'"
echo ""
echo "📺 Then Add EPG Provider:"
echo "  1. Click '+' next to 'TV Guide Data Providers'"
echo "  2. Select 'XMLTV'"
echo "  3. Use file: /config/epg_us.xml"
echo "  4. Click 'Save'"
echo ""
echo "🎯 This will give you:"
echo "  - Free TV channels (from M3U files)"
echo "  - Program guide (from EPG XML files)"
echo ""
echo "💡 The M3U files contain the actual TV channels"
echo "   The EPG XML files contain the program schedule"
