#!/bin/bash

# CLOUDFLARE SSL CERTIFICATE FIX
# Fixes HTTP 526 errors by correcting Cloudflare SSL settings

echo "🔐 CLOUDFLARE SSL CERTIFICATE FIX"
echo "================================="
echo ""

echo "🔍 CURRENT CERTIFICATE STATUS:"
echo "=============================="
echo "✅ Main domain (simondatalab.de): HTTP 200"
echo "❌ Moodle (moodle.simondatalab.de): HTTP 526"
echo "❌ Grafana (grafana.simondatalab.de): HTTP 526"
echo "❌ Jellyfin (jellyfin.simondatalab.de): HTTP 526"
echo "❌ Nextcloud (nextcloud.simondatalab.de): HTTP 526"
echo ""

echo "🚨 ROOT CAUSE IDENTIFIED:"
echo "========================"
echo "Multiple services showing HTTP 526 errors"
echo "This indicates Cloudflare SSL configuration issues:"
echo "1. SSL mode set to 'Flexible' instead of 'Full'"
echo "2. Origin server SSL configuration mismatch"
echo "3. Cloudflare cannot establish SSL connection to origin"
echo ""

echo "🛠️  CLOUDFLARE SSL FIX STRATEGY:"
echo "==============================="
echo ""

echo "STEP 1: Update Cloudflare SSL Mode"
echo "----------------------------------"
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Select each affected domain:"
echo "   - moodle.simondatalab.de"
echo "   - grafana.simondatalab.de"
echo "   - jellyfin.simondatalab.de"
echo "   - nextcloud.simondatalab.de"
echo "3. Navigate to: SSL/TLS > Overview"
echo "4. Change SSL mode from 'Flexible' to 'Full'"
echo "   - Flexible: Cloudflare ↔ HTTPS, Origin ↔ HTTP"
echo "   - Full: Cloudflare ↔ HTTPS, Origin ↔ HTTPS"
echo "   - Full (strict): Cloudflare ↔ HTTPS, Origin ↔ HTTPS (valid cert)"
echo ""

echo "STEP 2: Configure Origin Server SSL"
echo "----------------------------------"
echo "1. Go to: SSL/TLS > Origin Server"
echo "2. Enable 'Authenticated Origin Pulls'"
echo "3. Or configure 'Origin Certificates'"
echo "4. Verify origin server certificate"
echo ""

echo "STEP 3: Test SSL Configuration"
echo "-----------------------------"
echo "1. Wait 2-3 minutes for changes to propagate"
echo "2. Test each service:"
echo "   curl -I https://moodle.simondatalab.de/"
echo "   curl -I https://grafana.simondatalab.de/"
echo "   curl -I https://jellyfin.simondatalab.de/"
echo "   curl -I https://nextcloud.simondatalab.de/"
echo ""

echo "🔧 DOMAIN-SPECIFIC FIXES:"
echo "========================"
echo ""

echo "Moodle (moodle.simondatalab.de):"
echo "--------------------------------"
echo "1. Cloudflare SSL mode: 'Full'"
echo "2. Origin server: VM 9001 (10.0.0.104)"
echo "3. Check Apache SSL configuration"
echo "4. Verify SSL certificate on VM"
echo ""

echo "Grafana (grafana.simondatalab.de):"
echo "---------------------------------"
echo "1. Cloudflare SSL mode: 'Full'"
echo "2. Origin server: Check VM configuration"
echo "3. Verify Grafana SSL settings"
echo "4. Check reverse proxy configuration"
echo ""

echo "Jellyfin (jellyfin.simondatalab.de):"
echo "------------------------------------"
echo "1. Cloudflare SSL mode: 'Full'"
echo "2. Origin server: Check VM configuration"
echo "3. Verify Jellyfin SSL settings"
echo "4. Check reverse proxy configuration"
echo ""

echo "Nextcloud (nextcloud.simondatalab.de):"
echo "-------------------------------------"
echo "1. Cloudflare SSL mode: 'Full'"
echo "2. Origin server: Check VM configuration"
echo "3. Verify Nextcloud SSL settings"
echo "4. Check reverse proxy configuration"
echo ""

echo "🧪 TESTING SEQUENCE:"
echo "==================="
echo ""
echo "1. Test SSL handshake:"
echo "   openssl s_client -connect moodle.simondatalab.de:443 -servername moodle.simondatalab.de"
echo ""
echo "2. Test HTTPS status:"
echo "   curl -I https://moodle.simondatalab.de/"
echo ""
echo "3. Test certificate validity:"
echo "   echo | openssl s_client -connect moodle.simondatalab.de:443 2>/dev/null | openssl x509 -noout -dates"
echo ""

echo "📋 CLOUDFLARE DASHBOARD CHECKLIST:"
echo "================================="
echo ""
echo "For each affected domain:"
echo "□ SSL/TLS > Overview:"
echo "  □ SSL mode set to 'Full' or 'Full (strict)'"
echo "  □ NOT 'Flexible' or 'Off'"
echo ""
echo "□ SSL/TLS > Origin Server:"
echo "  □ 'Authenticated Origin Pulls' enabled"
echo "  □ Or 'Origin Certificates' configured"
echo ""
echo "□ SSL/TLS > Edge Certificates:"
echo "  □ 'Always Use HTTPS' enabled"
echo "  □ 'HTTP Strict Transport Security (HSTS)' enabled"
echo ""
echo "□ DNS > Records:"
echo "  □ A record points to correct IP"
echo "  □ Proxy status is 'Proxied' (orange cloud)"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "=================="
echo ""
echo "After fixing Cloudflare SSL settings:"
echo "✅ Moodle: HTTP 200 (instead of 526)"
echo "✅ Grafana: HTTP 200 (instead of 526)"
echo "✅ Jellyfin: HTTP 200 (instead of 526)"
echo "✅ Nextcloud: HTTP 200 (instead of 526)"
echo "✅ All services accessible via HTTPS"
echo "✅ SSL certificates working correctly"
echo ""

echo "🚨 COMMON CLOUDFLARE SSL ISSUES:"
echo "==============================="
echo ""
echo "1. SSL Mode 'Flexible':"
echo "   - Cloudflare expects HTTP from origin"
echo "   - But origin server is configured for HTTPS"
echo "   - Solution: Change to 'Full' mode"
echo ""
echo "2. Origin Server SSL Mismatch:"
echo "   - Cloudflare expects HTTPS from origin"
echo "   - But origin server SSL is not properly configured"
echo "   - Solution: Fix origin server SSL configuration"
echo ""
echo "3. Certificate Chain Issues:"
echo "   - Origin server certificate not trusted"
echo "   - Certificate doesn't match domain"
echo "   - Solution: Update origin server certificate"
echo ""

echo "🔄 MONITORING:"
echo "============="
echo ""
echo "Monitor SSL status for all services:"
echo "  watch -n 30 'curl -s -o /dev/null -w \"%{http_code}\" https://moodle.simondatalab.de/ && curl -s -o /dev/null -w \"%{http_code}\" https://grafana.simondatalab.de/ && curl -s -o /dev/null -w \"%{http_code}\" https://jellyfin.simondatalab.de/ && curl -s -o /dev/null -w \"%{http_code}\" https://nextcloud.simondatalab.de/'"
echo ""

echo "📞 IMMEDIATE ACTION PLAN:"
echo "========================"
echo ""
echo "1. Go to Cloudflare dashboard"
echo "2. Select each affected domain"
echo "3. Change SSL mode to 'Full'"
echo "4. Wait 2-3 minutes for propagation"
echo "5. Test all services"
echo "6. Verify SSL certificates"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./fix_cloudflare_ssl.sh"
