#!/bin/bash

# CHEG (CHANNEL GUIDE) CONFIGURATION FIX
# Fixes Jellyfin Live TV configuration issues

echo "📺 CHEG (CHANNEL GUIDE) CONFIGURATION FIX"
echo "========================================"
echo ""

echo "🔍 CURRENT ISSUES IDENTIFIED:"
echo "============================"
echo "❌ Tuner Devices shows: M3U /config/epg_us.xml"
echo "❌ This is WRONG - epg_us.xml is an EPG file, not a tuner!"
echo "❌ EPG file is being used as a channel source"
echo ""

echo "✅ CORRECT CONFIGURATION:"
echo "========================="
echo ""
echo "Tuner Devices (Channel Sources):"
echo "  M3U /config/samsung_tv_plus.m3u"
echo "  M3U /config/plex_live.m3u"
echo "  M3U /config/tubi_tv.m3u"
echo "  M3U /config/pluto_tv.m3u"
echo ""
echo "TV Guide Data Providers (EPG Sources):"
echo "  XMLTV /config/epg_us.xml"
echo "  XMLTV /config/epg_uk.xml"
echo ""

echo "🔧 STEP-BY-STEP FIX:"
echo "==================="
echo ""

echo "STEP 1: Remove Incorrect Tuner"
echo "-----------------------------"
echo "1. Go to Jellyfin Admin Panel"
echo "2. Navigate to: Dashboard → Live TV"
echo "3. Find the tuner with '/config/epg_us.xml'"
echo "4. Click the 'X' or 'Delete' button to remove it"
echo "5. Confirm deletion"
echo ""

echo "STEP 2: Add Correct Tuner Devices"
echo "---------------------------------"
echo "1. Click '+' next to 'Tuner Devices'"
echo "2. Select 'M3U Tuner'"
echo "3. Configure each tuner:"
echo ""
echo "   Tuner 1: Samsung TV Plus"
echo "   - Name: Samsung TV Plus"
echo "   - M3U URL: /config/samsung_tv_plus.m3u"
echo "   - Click 'Save'"
echo ""
echo "   Tuner 2: Plex Live"
echo "   - Name: Plex Live"
echo "   - M3U URL: /config/plex_live.m3u"
echo "   - Click 'Save'"
echo ""
echo "   Tuner 3: Tubi TV"
echo "   - Name: Tubi TV"
echo "   - M3U URL: /config/tubi_tv.m3u"
echo "   - Click 'Save'"
echo ""

echo "STEP 3: Add EPG Provider"
echo "----------------------"
echo "1. Click '+' next to 'TV Guide Data Providers'"
echo "2. Select 'XMLTV'"
echo "3. Configure EPG:"
echo "   - Name: US EPG"
echo "   - XMLTV URL: /config/epg_us.xml"
echo "   - Click 'Save'"
echo ""

echo "STEP 4: Map Channels to EPG"
echo "--------------------------"
echo "1. Go to 'Channel Mapping'"
echo "2. Map each channel to its EPG data"
echo "3. Ensure channel names match EPG entries"
echo "4. Save mapping"
echo ""

echo "🧪 VERIFICATION STEPS:"
echo "====================="
echo ""
echo "1. Check Tuner Devices:"
echo "   - Should show M3U files (not EPG files)"
echo "   - Should show channel counts"
echo "   - Should show 'Active' status"
echo ""
echo "2. Check TV Guide Data Providers:"
echo "   - Should show XMLTV files"
echo "   - Should show program data"
echo "   - Should show 'Active' status"
echo ""
echo "3. Check Channels:"
echo "   - Should show actual TV channels"
echo "   - Should have program guide data"
echo "   - Should be playable"
echo ""

echo "📁 REQUIRED FILES:"
echo "================="
echo ""
echo "M3U Files (Channel Sources):"
echo "  /config/samsung_tv_plus.m3u"
echo "  /config/plex_live.m3u"
echo "  /config/tubi_tv.m3u"
echo "  /config/pluto_tv.m3u"
echo ""
echo "EPG Files (Program Guide):"
echo "  /config/epg_us.xml"
echo "  /config/epg_uk.xml"
echo ""

echo "🔍 TROUBLESHOOTING:"
echo "=================="
echo ""
echo "If channels don't appear:"
echo "1. Check M3U file format"
echo "2. Verify file paths are correct"
echo "3. Check file permissions"
echo "4. Restart Jellyfin service"
echo ""
echo "If EPG doesn't work:"
echo "1. Check XMLTV file format"
echo "2. Verify channel mapping"
echo "3. Check EPG refresh schedule"
echo "4. Clear EPG cache"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "=================="
echo ""
echo "After fixing configuration:"
echo "✅ Tuner Devices show M3U files (not EPG files)"
echo "✅ TV Guide Data Providers show XMLTV files"
echo "✅ Channels are playable"
echo "✅ Program guide shows schedule"
echo "✅ Live TV works correctly"
echo ""

echo "💡 KEY CONCEPTS:"
echo "==============="
echo ""
echo "M3U Files = Channel Sources (what to watch)"
echo "EPG Files = Program Guide (when to watch)"
echo ""
echo "Tuner Devices = Where channels come from"
echo "TV Guide Data Providers = Where schedule comes from"
echo ""

echo "🔄 MONITORING:"
echo "============="
echo ""
echo "Check configuration status:"
echo "1. Go to Dashboard → Live TV"
echo "2. Check tuner status"
echo "3. Check EPG status"
echo "4. Test channel playback"
echo ""

echo "📞 SUPPORT:"
echo "==========="
echo ""
echo "If issues persist:"
echo "1. Check Jellyfin logs"
echo "2. Verify file formats"
echo "3. Test M3U files manually"
echo "4. Check network connectivity"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./fix_cheg_config.sh"
