#!/bin/bash

echo "🔧 Quick Fix: Add iptv-org EPG to Jellyfin"
echo "=========================================="
echo ""
echo "❌ Current Issue:"
echo "  Path '/config/iptv_org_epg_us.xml' not found"
echo "  The EPG file hasn't been uploaded to Jellyfin yet"
echo ""
echo "✅ Solution: Manual Upload"
echo "========================="
echo ""
echo "📥 Step 1: Download EPG File"
echo "-----------------------------"
echo "Download this file to your local machine:"
echo "https://iptv-org.github.io/epg/guides/us.xml"
echo ""
echo "📤 Step 2: Upload to VM"
echo "----------------------"
echo "Upload the downloaded file to your VM using:"
echo "- SCP: scp epg_us.xml simonadmin@10.0.0.103:/tmp/"
echo "- SFTP: Use any SFTP client"
echo "- Or copy/paste the content"
echo ""
echo "🔧 Step 3: Copy to Jellyfin Container"
echo "-------------------------------------"
echo "Run these commands on your VM:"
echo ""
echo "docker cp /tmp/epg_us.xml jellyfin-simonadmin:/config/iptv_org_epg_us.xml"
echo "docker exec jellyfin-simonadmin chown jellyfin:jellyfin /config/iptv_org_epg_us.xml"
echo "docker exec jellyfin-simonadmin ls -la /config/iptv_org_epg_us.xml"
echo ""
echo "🌐 Step 4: Configure in Jellyfin"
echo "-------------------------------"
echo "1. Go to: http://136.243.155.166:8096/web/"
echo "2. Log in as: simonadmin"
echo "3. Go to Admin Panel → Live TV"
echo "4. Click '+' next to 'TV Guide Data Providers'"
echo "5. Select 'XMLTV'"
echo "6. Use file: /config/iptv_org_epg_us.xml"
echo "7. Click 'Save'"
echo ""
echo "💡 Alternative: Use Existing EPG Files"
echo "======================================"
echo "You already have these EPG files in your container:"
echo "- /config/epg_us.xml"
echo "- /config/epg_uk.xml"
echo "- /config/epg_de.xml"
echo "- /config/epg_fr.xml"
echo "- /config/epg_ca.xml"
echo "- /config/epg_au.xml"
echo "- /config/epg_jp.xml"
echo "- /config/epg_kr.xml"
echo "- /config/epg_in.xml"
echo "- /config/epg_br.xml"
echo "- /config/epg_mx.xml"
echo "- /config/epg_es.xml"
echo "- /config/epg_it.xml"
echo "- /config/epg_nl.xml"
echo "- /config/epg_ru.xml"
echo "- /config/epg_cn.xml"
echo "- /config/epg_ae.xml"
echo "- /config/epg_ar.xml"
echo "- /config/epg_eg.xml"
echo "- /config/epg_sa.xml"
echo ""
echo "🎯 Quick Fix: Use Existing File"
echo "=============================="
echo "Instead of '/config/iptv_org_epg_us.xml', use:"
echo "/config/epg_us.xml"
echo ""
echo "This file is already in your container and ready to use!"
