#!/bin/bash

# CLOUDFLARE TUNNEL SSL FIX SCRIPT
# Fixes SSL issues based on your tunnel configuration

echo "🔐 CLOUDFLARE TUNNEL SSL FIX SCRIPT"
echo "==================================="
echo ""

echo "🔍 ANALYZING YOUR TUNNEL CONFIGURATION:"
echo "======================================"
echo ""
echo "✅ Cloudflare Tunnel Routes Found:"
echo "  1. simondatalab.de → http://10.0.0.150:80"
echo "  2. www.simondatalab.de → http://10.0.0.150:80"
echo "  3. moodle.simondatalab.de → http://10.0.0.104:8086"
echo "  4. grafana.simondatalab.de → http://10.0.0.104:3000"
echo "  5. openwebui.simondatalab.de → http://10.0.0.111:3001"
echo "  6. geoneuralviz.simondatalab.de → http://10.0.0.106:8080"
echo "  7. booklore.simondatalab.de → http://10.0.0.103:6060"
echo "  8. ollama.simondatalab.de → http://10.0.0.111:11434"
echo "  9. mlflow.simondatalab.de → http://10.0.0.111:5000"
echo ""

echo "🚨 ISSUE IDENTIFIED:"
echo "==================="
echo "❌ SSL/TLS mode is likely set to 'Flexible'"
echo "❌ Tunnel routes use HTTP (not HTTPS) to origin servers"
echo "❌ This causes HTTP 526 errors when SSL mode is 'Flexible'"
echo ""

echo "🛠️  SSL MODE FIX STRATEGY:"
echo "========================="
echo ""

echo "CURRENT SSL MODES AVAILABLE:"
echo "---------------------------"
echo "1. Automatic SSL/TLS (default) - Cloudflare manages automatically"
echo "2. Strict (SSL-Only Origin Pull) - Enforce HTTPS to origin"
echo "3. Full (Strict) - HTTPS + valid certificates"
echo "4. Full - HTTPS but allows self-signed certificates"
echo "5. Flexible - HTTPS to visitors, HTTP to origin"
echo "6. Off (not secure) - No encryption"
echo ""

echo "🎯 RECOMMENDED FIX:"
echo "=================="
echo ""
echo "Since your tunnel routes use HTTP to origin servers:"
echo "✅ Use 'Flexible' mode for tunnel routes"
echo "✅ This allows HTTP connections to origin (10.0.0.x:port)"
echo "✅ But provides HTTPS to visitors"
echo ""

echo "🔧 STEP-BY-STEP FIX:"
echo "==================="
echo ""
echo "STEP 1: Set SSL Mode to 'Flexible'"
echo "---------------------------------"
echo "1. Go to Cloudflare dashboard"
echo "2. Select simondatalab.de"
echo "3. Go to SSL/TLS > Overview"
echo "4. Select 'Custom SSL/TLS'"
echo "5. Choose 'Flexible' mode"
echo "6. Save changes"
echo ""

echo "STEP 2: Verify Tunnel Routes"
echo "---------------------------"
echo "Your tunnel routes are correctly configured:"
echo "  - moodle.simondatalab.de → http://10.0.0.104:8086"
echo "  - grafana.simondatalab.de → http://10.0.0.104:3000"
echo "  - All other services → correct internal IPs"
echo ""

echo "STEP 3: Check VM 9001 (10.0.0.104)"
echo "---------------------------------"
echo "Since Moodle was working yesterday, check:"
echo "1. NAT rules on VM 9001"
echo "2. Nginx configuration"
echo "3. IP rules/firewall"
echo "4. Service status on ports 8086 and 3000"
echo ""

echo "🧪 TESTING COMMANDS:"
echo "==================="
echo ""
echo "Test tunnel routes:"
echo "  curl -I https://moodle.simondatalab.de/"
echo "  curl -I https://grafana.simondatalab.de/"
echo "  curl -I https://openwebui.simondatalab.de/"
echo ""
echo "Test internal connections:"
echo "  curl -I http://10.0.0.104:8086/"
echo "  curl -I http://10.0.0.104:3000/"
echo ""

echo "🔍 VM 9001 DIAGNOSTICS:"
echo "======================"
echo ""
echo "Check NAT rules:"
echo "  iptables -t nat -L -n -v"
echo ""
echo "Check Nginx status:"
echo "  systemctl status nginx"
echo "  nginx -t"
echo ""
echo "Check IP rules:"
echo "  iptables -L -n -v"
echo ""
echo "Check service ports:"
echo "  netstat -tlnp | grep -E ':(8086|3000)'"
echo ""

echo "📋 TUNNEL CONFIGURATION CHECKLIST:"
echo "================================="
echo ""
echo "□ SSL/TLS mode set to 'Flexible'"
echo "□ Tunnel routes point to correct internal IPs"
echo "□ Internal services running on correct ports"
echo "□ NAT rules allow traffic to internal services"
echo "□ Nginx configured for reverse proxy"
echo "□ Firewall rules allow internal traffic"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "=================="
echo ""
echo "After fixing SSL mode to 'Flexible':"
echo "✅ All tunnel routes return HTTP 200"
echo "✅ Services accessible via HTTPS"
echo "✅ Internal HTTP connections work"
echo "✅ No more HTTP 526 errors"
echo ""

echo "🚨 COMMON TUNNEL ISSUES:"
echo "======================="
echo ""
echo "1. SSL Mode Mismatch:"
echo "   - 'Full' mode expects HTTPS to origin"
echo "   - But tunnel routes use HTTP"
echo "   - Solution: Use 'Flexible' mode"
echo ""
echo "2. Internal Service Issues:"
echo "   - Services not running on internal ports"
echo "   - NAT rules blocking traffic"
echo "   - Solution: Check VM configuration"
echo ""
echo "3. Tunnel Route Problems:"
echo "   - Wrong internal IPs"
echo "   - Wrong ports"
echo "   - Solution: Verify tunnel configuration"
echo ""

echo "🔄 MONITORING:"
echo "============="
echo ""
echo "Monitor tunnel status:"
echo "  watch -n 30 'curl -s -o /dev/null -w \"%{http_code}\" https://moodle.simondatalab.de/'"
echo ""
echo "Check tunnel logs:"
echo "  # Check Cloudflare tunnel logs in dashboard"
echo ""

echo "📞 IMMEDIATE ACTION:"
echo "==================="
echo ""
echo "1. Set SSL mode to 'Flexible' in Cloudflare dashboard"
echo "2. Check VM 9001 (10.0.0.104) services"
echo "3. Verify NAT rules and Nginx configuration"
echo "4. Test tunnel routes"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./fix_tunnel_ssl.sh"
