#!/bin/bash

echo "📺 Manual Guide: Adding iptv-org EPG to Jellyfin"
echo "==============================================="
echo ""
echo "🔗 iptv-org EPG Repository: https://github.com/iptv-org/epg/tree/master"
echo ""
echo "📥 Step 1: Download EPG Files"
echo "=============================="
echo "Download these EPG files from iptv-org:"
echo ""
echo "🌍 Regional EPG URLs:"
echo "  US:  https://iptv-org.github.io/epg/guides/us.xml"
echo "  UK:  https://iptv-org.github.io/epg/guides/uk.xml"
echo "  DE:  https://iptv-org.github.io/epg/guides/de.xml"
echo "  FR:  https://iptv-org.github.io/epg/guides/fr.xml"
echo "  CA:  https://iptv-org.github.io/epg/guides/ca.xml"
echo "  AU:  https://iptv-org.github.io/epg/guides/au.xml"
echo "  JP:  https://iptv-org.github.io/epg/guides/jp.xml"
echo "  KR:  https://iptv-org.github.io/epg/guides/kr.xml"
echo "  IN:  https://iptv-org.github.io/epg/guides/in.xml"
echo "  BR:  https://iptv-org.github.io/epg/guides/br.xml"
echo "  MX:  https://iptv-org.github.io/epg/guides/mx.xml"
echo "  ES:  https://iptv-org.github.io/epg/guides/es.xml"
echo "  IT:  https://iptv-org.github.io/epg/guides/it.xml"
echo "  NL:  https://iptv-org.github.io/epg/guides/nl.xml"
echo "  RU:  https://iptv-org.github.io/epg/guides/ru.xml"
echo "  CN:  https://iptv-org.github.io/epg/guides/cn.xml"
echo "  AE:  https://iptv-org.github.io/epg/guides/ae.xml"
echo "  AR:  https://iptv-org.github.io/epg/guides/ar.xml"
echo "  EG:  https://iptv-org.github.io/epg/guides/eg.xml"
echo "  SA:  https://iptv-org.github.io/epg/guides/sa.xml"
echo ""
echo "📤 Step 2: Upload to VM"
echo "======================"
echo "1. Download the EPG files to your local machine"
echo "2. Upload them to your VM using SCP or SFTP"
echo "3. Place them in a temporary directory like /tmp/"
echo ""
echo "🔧 Step 3: Copy to Jellyfin Container"
echo "====================================="
echo "Run these commands on your VM:"
echo ""
echo "# Copy EPG files to Jellyfin container"
echo "docker cp /tmp/epg_us.xml jellyfin-simonadmin:/config/iptv_org_epg_us.xml"
echo "docker cp /tmp/epg_uk.xml jellyfin-simonadmin:/config/iptv_org_epg_uk.xml"
echo "docker cp /tmp/epg_de.xml jellyfin-simonadmin:/config/iptv_org_epg_de.xml"
echo "# ... repeat for other regions"
echo ""
echo "# Set permissions"
echo "docker exec jellyfin-simonadmin chown jellyfin:jellyfin /config/iptv_org_epg_*.xml"
echo ""
echo "🌐 Step 4: Configure in Jellyfin Web Interface"
echo "=============================================="
echo "1. Go to: http://136.243.155.166:8096/web/"
echo "2. Log in as: simonadmin"
echo "3. Go to Admin Panel → Live TV"
echo "4. Click '+' next to 'TV Guide Data Providers'"
echo "5. Select 'XMLTV'"
echo "6. Use file: /config/iptv_org_epg_us.xml"
echo "7. Click 'Save'"
echo "8. Repeat for other regions as needed"
echo ""
echo "🔄 Step 5: Refresh Guide Data"
echo "============================"
echo "1. Click 'Refresh Guide Data' button"
echo "2. Wait for the guide to populate"
echo "3. Access Live TV from main menu"
echo ""
echo "💡 Quick Start Recommendation:"
echo "============================="
echo "Start with just the US EPG:"
echo "1. Download: https://iptv-org.github.io/epg/guides/us.xml"
echo "2. Upload to VM and copy to container"
echo "3. Configure in Jellyfin web interface"
echo "4. Test with your existing M3U tuners"
echo ""
echo "🎯 Benefits of iptv-org EPG:"
echo "==========================="
echo "✅ Thousands of TV channels"
echo "✅ Hundreds of sources"
echo "✅ Regular updates"
echo "✅ Multiple regions"
echo "✅ Free and open source"
echo ""
echo "📚 More Information:"
echo "==================="
echo "Repository: https://github.com/iptv-org/epg"
echo "Documentation: https://iptv-org.github.io/epg/"
echo "API: https://iptv-org.github.io/api/"
