#!/bin/bash

echo "📺 Jellyfin Live TV Configuration Helper"
echo "======================================="
echo ""
echo "❌ Current Issue:"
echo "  You're trying to use '/config/epg_us.xml' as an M3U tuner"
echo "  This is an EPG (guide) file, not a channel playlist"
echo ""
echo "✅ Correct Configuration:"
echo ""
echo "For M3U Tuner Setup:"
echo "  Tuner type: M3U Tuner"
echo "  File or URL: /config/samsung_tv_plus.m3u"
echo "  (or /config/plex_live.m3u, or /config/tubi_tv.m3u)"
echo ""
echo "For TV Guide Data Providers:"
echo "  Type: XMLTV"
echo "  File or URL: /config/epg_us.xml"
echo "  (or any other epg_*.xml file)"
echo ""
echo "📁 Available M3U Files:"
echo "  - /config/samsung_tv_plus.m3u"
echo "  - /config/plex_live.m3u"
echo "  - /config/tubi_tv.m3u"
echo ""
echo "📁 Available EPG Files:"
echo "  - /config/epg_us.xml (United States)"
echo "  - /config/epg_uk.xml (United Kingdom)"
echo "  - /config/epg_de.xml (Germany)"
echo "  - /config/epg_fr.xml (France)"
echo "  - /config/epg_ca.xml (Canada)"
echo "  - /config/epg_au.xml (Australia)"
echo "  - /config/epg_jp.xml (Japan)"
echo "  - /config/epg_kr.xml (South Korea)"
echo "  - /config/epg_in.xml (India)"
echo "  - /config/epg_br.xml (Brazil)"
echo "  - /config/epg_mx.xml (Mexico)"
echo "  - /config/epg_es.xml (Spain)"
echo "  - /config/epg_it.xml (Italy)"
echo "  - /config/epg_nl.xml (Netherlands)"
echo "  - /config/epg_ru.xml (Russia)"
echo "  - /config/epg_cn.xml (China)"
echo "  - /config/epg_ae.xml (UAE)"
echo "  - /config/epg_ar.xml (Argentina)"
echo "  - /config/epg_eg.xml (Egypt)"
echo "  - /config/epg_sa.xml (Saudi Arabia)"
echo ""
echo "🔧 Setup Steps:"
echo "  1. For M3U Tuner: Use one of the .m3u files above"
echo "  2. For EPG Provider: Use one of the epg_*.xml files above"
echo "  3. You can add multiple tuners and EPG providers"
echo ""
echo "💡 Recommendation:"
echo "  Start with: /config/samsung_tv_plus.m3u"
echo "  EPG: /config/epg_us.xml"
echo ""
echo "🎯 This will give you free US channels with program guide!"
