#!/bin/bash
# Add Movies and TV Shows libraries to Jellyfin

set -e

API_KEY="${JELLYFIN_API_KEY:-f870ddf763334cfba15fb45b091b10a8}"
JELLYFIN_URL="${JELLYFIN_URL:-http://136.243.155.166:8096}"

echo "=========================================="
echo "Jellyfin Media Library Configuration"
echo "=========================================="
echo ""

# Check media folder
MEDIA_FOLDER="/home/simon/Videos"
if [ ! -d "$MEDIA_FOLDER" ]; then
    echo "❌ Media folder not found: $MEDIA_FOLDER"
    exit 1
fi

echo "✅ Media folder found: $MEDIA_FOLDER"
echo ""

# List current libraries
echo "Current Jellyfin Libraries:"
echo "-------------------------------------------"
curl -s -X GET \
    "$JELLYFIN_URL/Library/VirtualFolders" \
    -H "X-Emby-Token: $API_KEY" | \
    python3 -c "import sys, json; libs = json.load(sys.stdin); [print(f\"  - {lib['Name']} ({lib.get('CollectionType', 'mixed')}): {', '.join([loc['Path'] for loc in lib.get('Locations', [])])}\") for lib in libs]"
echo ""

echo "=========================================="
echo "Recommended Library Structure:"
echo "=========================================="
echo ""
echo "For best results, organize media as:"
echo ""
echo "/home/simon/Videos/"
echo "├── Movies/"
echo "│   ├── Movie Name (Year)/"
echo "│   │   └── Movie Name (Year).mkv"
echo "│   └── Another Movie (Year)/"
echo "│       └── Another Movie (Year).mp4"
echo "└── TV Shows/"
echo "    ├── Show Name/"
echo "    │   ├── Season 01/"
echo "    │   │   ├── Show Name - S01E01.mkv"
echo "    │   │   └── Show Name - S01E02.mkv"
echo "    │   └── Season 02/"
echo "    │       └── Show Name - S02E01.mkv"
echo ""

echo "=========================================="
echo "Current Media Files:"
echo "=========================================="
echo ""
find "$MEDIA_FOLDER" -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.avi" -o -name "*.mov" \) 2>/dev/null | head -20 || echo "No video files found"
echo ""

echo "=========================================="
echo "To Add Libraries via Jellyfin Web UI:"
echo "=========================================="
echo ""
echo "1. Open Jellyfin: http://136.243.155.166:8096"
echo "2. Go to: Dashboard → Libraries"
echo "3. Click: Add Library"
echo "4. Configure:"
echo ""
echo "   For Movies:"
echo "   - Content type: Movies"
echo "   - Display name: Movies"
echo "   - Folder: /home/simon/Videos/Movies"
echo "   - Preferred language: English"
echo "   - Country: United States"
echo ""
echo "   For TV Shows:"
echo "   - Content type: Shows"
echo "   - Display name: TV Shows"
echo "   - Folder: /home/simon/Videos/TV Shows"
echo "   - Preferred language: English"
echo "   - Country: United States"
echo ""
echo "5. Click: OK"
echo "6. Click: Scan All Libraries"
echo ""

echo "=========================================="
echo "Recommended Playback Settings (Already Set):"
echo "=========================================="
echo ""
echo "✅ Audio Settings:"
echo "   - Maximum Channels: Auto"
echo "   - Preferred Language: Any"
echo "   - Disable VBR: Enabled (for compatibility)"
echo ""
echo "✅ Video Quality:"
echo "   - Home network: Auto"
echo "   - Max Resolution: Auto"
echo "   - Prefer fMP4-HLS: Enabled (for HEVC/AV1)"
echo ""
echo "✅ Playback Features:"
echo "   - Cinema mode: Enabled (trailers)"
echo "   - Auto play next: Enabled"
echo "   - Skip forward: 30 seconds"
echo "   - Skip back: 10 seconds"
echo "   - Intro skip: Ask to skip"
echo "   - Outro skip: Ask to skip"
echo ""
echo "✅ Advanced Video:"
echo "   - DTS: Enabled (if supported)"
echo "   - TrueHD: Enabled (if supported)"
echo "   - Transcode codec: Auto"
echo ""
echo "✅ Advanced Audio:"
echo "   - Audio Normalization: Track Gain"
echo "   - Remux FLAC: Enabled (if needed)"
echo "   - Remux MP3: Enabled (if needed)"
echo ""

echo "Your settings look perfect for high-quality playback!"
echo ""
