#!/bin/bash

echo "📺 Manual Live TV Setup Guide for Jellyfin"
echo "========================================="

echo "🎯 You're now at the Jellyfin home page!"
echo "Next steps to add Live TV channels:"
echo ""
echo "📋 Step 1: Navigate to Live TV Settings"
echo "======================================"
echo "1. Click on the ⚙️ Settings gear icon (top right corner)"
echo "2. In the left sidebar, click on 'Live TV'"
echo "3. You should see the Live TV configuration page"
echo ""
echo "📋 Step 2: Add M3U Tuner"
echo "======================="
echo "1. Click 'Add TV Provider' or 'Add Tuner' button"
echo "2. Select 'M3U Tuner' as the tuner type"
echo "3. Fill in the following details:"
echo ""
echo "   📝 Tuner Configuration:"
echo "   ======================"
echo "   • Name: iptv-org Global"
echo "   • File or URL: https://iptv-org.github.io/iptv/index.m3u"
echo "   • User agent: Jellyfin/10.10.7"
echo "   • Simultaneous stream limit: 0"
echo "   • Fallback max stream bitrate: 30"
echo "   • Allow fMP4 transcoding container: ✅ (checked)"
echo "   • Allow stream sharing: ✅ (checked)"
echo "   • Auto-loop live streams: ❌ (unchecked)"
echo "   • Ignore DTS: ❌ (unchecked)"
echo ""
echo "4. Click 'Save'"
echo ""
echo "📋 Step 3: Add Additional Tuners (Optional)"
echo "=========================================="
echo "You can add more tuners for different channel categories:"
echo ""
echo "🇺🇸 US Channels:"
echo "   • Name: iptv-org US Channels"
echo "   • URL: https://iptv-org.github.io/iptv/countries/us.m3u"
echo ""
echo "📰 News Channels:"
echo "   • Name: iptv-org News"
echo "   • URL: https://iptv-org.github.io/iptv/categories/news.m3u"
echo ""
echo "⚽ Sports Channels:"
echo "   • Name: iptv-org Sports"
echo "   • URL: https://iptv-org.github.io/iptv/categories/sports.m3u"
echo ""
echo "🎬 Movies Channels:"
echo "   • Name: iptv-org Movies"
echo "   • URL: https://iptv-org.github.io/iptv/categories/movies.m3u"
echo ""
echo "📋 Step 4: Verify Setup"
echo "====================="
echo "1. After adding tuners, go to 'Live TV' in the main menu"
echo "2. You should see your channels appear"
echo "3. If channels don't appear immediately, wait 5-10 minutes"
echo "4. Try refreshing the page"
echo ""
echo "🎉 Expected Results:"
echo "==================="
echo "✅ 1000+ free TV channels from around the world"
echo "✅ News, sports, movies, entertainment channels"
echo "✅ Channels from multiple countries and languages"
echo "✅ Always up-to-date channel list"
echo ""
echo "🔧 Troubleshooting:"
echo "=================="
echo "If you get 'There was an error saving the TV provider':"
echo "1. Try a different URL (use the US channels URL)"
echo "2. Check your internet connection"
echo "3. Try refreshing the page and logging in again"
echo "4. Make sure all required fields are filled"
echo ""
echo "💡 Pro Tips:"
echo "==========="
echo "• Start with just one tuner (iptv-org Global)"
echo "• Test it works before adding more tuners"
echo "• The manual method bypasses the broken API"
echo "• You can always add more tuners later"
echo ""
echo "🚀 Ready to add your first tuner!"
echo "Go to Settings → Live TV → Add TV Provider → M3U Tuner"


