#!/bin/bash

# MOODLE SSL/TLS FIX SCRIPT
# Fixes the HTTP 526 error for moodle.simondatalab.de

echo "🎓 MOODLE SSL/TLS FIX SCRIPT"
echo "============================"
echo ""
echo "Target: moodle.simondatalab.de"
echo "VM: 9001 (10.0.0.104)"
echo "Issue: HTTP 526 - Cloudflare SSL/TLS handshake failure"
echo ""

echo "🔍 CURRENT STATUS:"
echo "================="
echo "✅ VM is running (confirmed on Proxmox)"
echo "✅ HTTP redirects to HTTPS (301)"
echo "❌ HTTPS returns 526 (SSL/TLS handshake failure)"
echo ""

echo "🚨 ROOT CAUSE:"
echo "============="
echo "Cloudflare cannot establish SSL/TLS connection to origin server"
echo "This is typically caused by:"
echo "1. SSL certificate issues on origin server"
echo "2. SSL configuration problems"
echo "3. Cloudflare SSL mode mismatch"
echo "4. Origin server SSL service not running"
echo ""

echo "🛠️  FIX STRATEGIES:"
echo "=================="
echo ""

echo "STRATEGY 1: Check Cloudflare SSL Settings"
echo "----------------------------------------"
echo "1. Go to Cloudflare dashboard"
echo "2. Select moodle.simondatalab.de"
echo "3. SSL/TLS > Overview"
echo "4. Check SSL mode:"
echo "   - Should be 'Full' or 'Full (strict)'"
echo "   - NOT 'Flexible' or 'Off'"
echo "5. SSL/TLS > Origin Server"
echo "6. Check 'Origin Certificates'"
echo ""

echo "STRATEGY 2: Fix Origin Server SSL"
echo "--------------------------------"
echo "1. Access VM via Proxmox console"
echo "2. Check SSL certificate:"
echo "   sudo openssl x509 -in /etc/ssl/certs/ssl-cert-snakeoil.pem -text -noout"
echo "3. Enable SSL modules:"
echo "   sudo a2enmod ssl"
echo "   sudo a2enmod rewrite"
echo "4. Check Apache SSL configuration:"
echo "   sudo nano /etc/apache2/sites-available/moodle.conf"
echo "5. Restart Apache:"
echo "   sudo systemctl restart apache2"
echo ""

echo "STRATEGY 3: Test SSL Connectivity"
echo "-------------------------------"
echo "1. Test local SSL:"
echo "   curl -I https://localhost/"
echo "2. Test with SNI:"
echo "   curl -I https://localhost/ -H 'Host: moodle.simondatalab.de'"
echo "3. Check SSL handshake:"
echo "   openssl s_client -connect localhost:443 -servername moodle.simondatalab.de"
echo ""

echo "🔧 DETAILED FIX COMMANDS:"
echo "========================"
echo ""

echo "VM Console Commands (via Proxmox):"
echo "----------------------------------"
echo "# Check Apache status"
echo "sudo systemctl status apache2"
echo ""
echo "# Check SSL modules"
echo "sudo a2enmod ssl"
echo "sudo a2enmod rewrite"
echo ""
echo "# Check SSL certificate"
echo "sudo openssl x509 -in /etc/ssl/certs/ssl-cert-snakeoil.pem -text -noout"
echo ""
echo "# Check Apache SSL configuration"
echo "sudo nano /etc/apache2/sites-available/moodle.conf"
echo ""
echo "# Restart Apache"
echo "sudo systemctl restart apache2"
echo ""
echo "# Test local SSL"
echo "curl -I https://localhost/"
echo ""

echo "Cloudflare Dashboard Settings:"
echo "-----------------------------"
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Select: moodle.simondatalab.de"
echo "3. SSL/TLS > Overview:"
echo "   - Set SSL mode to 'Full' (not 'Flexible')"
echo "4. SSL/TLS > Origin Server:"
echo "   - Enable 'Origin Certificates'"
echo "   - Or use 'Authenticated Origin Pulls'"
echo ""

echo "🧪 TESTING SEQUENCE:"
echo "==================="
echo ""
echo "1. Test VM SSL locally:"
echo "   curl -I https://10.0.0.104/"
echo ""
echo "2. Test with SNI:"
echo "   curl -I https://10.0.0.104/ -H 'Host: moodle.simondatalab.de'"
echo ""
echo "3. Test external access:"
echo "   curl -I https://moodle.simondatalab.de/"
echo ""

echo "📋 QUICK FIX CHECKLIST:"
echo "======================"
echo ""
echo "□ Check Cloudflare SSL mode (should be 'Full')"
echo "□ Verify origin server SSL certificate"
echo "□ Enable SSL modules on Apache"
echo "□ Check Apache SSL virtual host configuration"
echo "□ Restart Apache service"
echo "□ Test local SSL connectivity"
echo "□ Test external SSL connectivity"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "=================="
echo ""
echo "After fixes:"
echo "✅ HTTPS Status: 200 (instead of 526)"
echo "✅ Moodle login page loads correctly"
echo "✅ SSL certificate is valid"
echo "✅ Cloudflare can connect to origin server"
echo ""

echo "🚨 COMMON SSL ISSUES:"
echo "===================="
echo ""
echo "1. SSL Mode Mismatch:"
echo "   - Cloudflare 'Flexible' mode with HTTP origin"
echo "   - Should be 'Full' mode with HTTPS origin"
echo ""
echo "2. Invalid SSL Certificate:"
echo "   - Self-signed certificate not trusted"
echo "   - Certificate doesn't match domain"
echo "   - Certificate expired"
echo ""
echo "3. Apache SSL Configuration:"
echo "   - SSL modules not enabled"
echo "   - Virtual host not configured for SSL"
echo "   - Wrong certificate paths"
echo ""

echo "🔄 MONITORING:"
echo "============="
echo ""
echo "Monitor SSL status:"
echo "  watch -n 10 'curl -s -o /dev/null -w \"%{http_code}\" https://moodle.simondatalab.de/'"
echo ""
echo "Check SSL certificate:"
echo "  openssl s_client -connect moodle.simondatalab.de:443 -servername moodle.simondatalab.de"
echo ""

echo "📞 NEXT STEPS:"
echo "============="
echo ""
echo "1. Access VM via Proxmox console"
echo "2. Check and fix SSL configuration"
echo "3. Update Cloudflare SSL settings"
echo "4. Test SSL connectivity"
echo "5. Verify Moodle access"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./moodle_ssl_fix.sh"
