#!/bin/bash

# MOODLE CLOUDFLARE SSL FIX
# Fixes HTTP 526 error by correcting Cloudflare SSL settings

echo "🎓 MOODLE CLOUDFLARE SSL FIX"
echo "============================"
echo ""
echo "Target: moodle.simondatalab.de"
echo "Issue: HTTP 526 - Cloudflare SSL/TLS handshake failure"
echo ""

echo "🔍 ANALYSIS RESULTS:"
echo "==================="
echo "✅ VM is running (confirmed on Proxmox)"
echo "✅ HTTP redirects to HTTPS (301)"
echo "✅ SSL certificate is valid (Google Trust Services)"
echo "❌ HTTPS returns 526 (Cloudflare SSL configuration issue)"
echo ""

echo "🚨 ROOT CAUSE IDENTIFIED:"
echo "========================"
echo "The SSL certificate is valid, but Cloudflare cannot establish"
echo "a proper SSL/TLS connection to the origin server."
echo ""
echo "This is typically caused by:"
echo "1. Cloudflare SSL mode set to 'Flexible' instead of 'Full'"
echo "2. Origin server SSL configuration mismatch"
echo "3. Cloudflare SSL settings not properly configured"
echo ""

echo "🛠️  CLOUDFLARE SSL FIX:"
echo "======================="
echo ""
echo "STEP 1: Update Cloudflare SSL Mode"
echo "----------------------------------"
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Select: moodle.simondatalab.de"
echo "3. Navigate to: SSL/TLS > Overview"
echo "4. Change SSL mode from 'Flexible' to 'Full'"
echo "   - Flexible: Cloudflare ↔ HTTPS, Origin ↔ HTTP"
echo "   - Full: Cloudflare ↔ HTTPS, Origin ↔ HTTPS"
echo "   - Full (strict): Cloudflare ↔ HTTPS, Origin ↔ HTTPS (valid cert)"
echo ""

echo "STEP 2: Configure Origin Server SSL"
echo "----------------------------------"
echo "1. Go to: SSL/TLS > Origin Server"
echo "2. Enable 'Authenticated Origin Pulls'"
echo "3. Or configure 'Origin Certificates'"
echo "4. Verify origin server certificate"
echo ""

echo "STEP 3: Test SSL Configuration"
echo "-----------------------------"
echo "1. Wait 2-3 minutes for changes to propagate"
echo "2. Test HTTPS access:"
echo "   curl -I https://moodle.simondatalab.de/"
echo "3. Check SSL certificate:"
echo "   openssl s_client -connect moodle.simondatalab.de:443"
echo ""

echo "🔧 ALTERNATIVE FIXES:"
echo "===================="
echo ""
echo "If Cloudflare SSL mode is already 'Full':"
echo "1. Check origin server SSL configuration"
echo "2. Verify Apache SSL virtual host"
echo "3. Check SSL certificate paths"
echo "4. Restart Apache service"
echo ""

echo "If SSL mode is 'Full (strict)':"
echo "1. Verify origin server certificate is valid"
echo "2. Check certificate chain"
echo "3. Ensure certificate matches domain"
echo "4. Update certificate if expired"
echo ""

echo "🧪 TESTING COMMANDS:"
echo "==================="
echo ""
echo "Test current SSL status:"
echo "  curl -I https://moodle.simondatalab.de/"
echo ""
echo "Test SSL certificate:"
echo "  openssl s_client -connect moodle.simondatalab.de:443 -servername moodle.simondatalab.de"
echo ""
echo "Test with different SSL modes:"
echo "  # Test if it's a Cloudflare SSL mode issue"
echo "  curl -I https://moodle.simondatalab.de/ -H 'CF-Connecting-IP: 1.2.3.4'"
echo ""

echo "📋 CLOUDFLARE DASHBOARD CHECKLIST:"
echo "================================="
echo ""
echo "□ SSL/TLS > Overview:"
echo "  □ SSL mode set to 'Full' or 'Full (strict)'"
echo "  □ NOT 'Flexible' or 'Off'"
echo ""
echo "□ SSL/TLS > Origin Server:"
echo "  □ 'Authenticated Origin Pulls' enabled"
echo "  □ Or 'Origin Certificates' configured"
echo ""
echo "□ SSL/TLS > Edge Certificates:"
echo "  □ 'Always Use HTTPS' enabled"
echo "  □ 'HTTP Strict Transport Security (HSTS)' enabled"
echo ""
echo "□ DNS > Records:"
echo "  □ A record points to 10.0.0.104"
echo "  □ Proxy status is 'Proxied' (orange cloud)"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "=================="
echo ""
echo "After fixing Cloudflare SSL settings:"
echo "✅ HTTPS Status: 200 (instead of 526)"
echo "✅ Moodle login page loads correctly"
echo "✅ SSL certificate is valid"
echo "✅ Cloudflare can connect to origin server"
echo ""

echo "🚨 COMMON CLOUDFLARE SSL ISSUES:"
echo "==============================="
echo ""
echo "1. SSL Mode 'Flexible':"
echo "   - Cloudflare expects HTTP from origin"
echo "   - But origin server is configured for HTTPS"
echo "   - Solution: Change to 'Full' mode"
echo ""
echo "2. Origin Server SSL Mismatch:"
echo "   - Cloudflare expects HTTPS from origin"
echo "   - But origin server SSL is not properly configured"
echo "   - Solution: Fix origin server SSL configuration"
echo ""
echo "3. Certificate Chain Issues:"
echo "   - Origin server certificate not trusted"
echo "   - Certificate doesn't match domain"
echo "   - Solution: Update origin server certificate"
echo ""

echo "🔄 MONITORING:"
echo "============="
echo ""
echo "Monitor SSL status:"
echo "  watch -n 10 'curl -s -o /dev/null -w \"%{http_code}\" https://moodle.simondatalab.de/'"
echo ""
echo "Check SSL certificate:"
echo "  openssl s_client -connect moodle.simondatalab.de:443 -servername moodle.simondatalab.de"
echo ""

echo "📞 IMMEDIATE ACTION:"
echo "==================="
echo ""
echo "1. Go to Cloudflare dashboard"
echo "2. Select moodle.simondatalab.de"
echo "3. Change SSL mode to 'Full'"
echo "4. Wait 2-3 minutes"
echo "5. Test HTTPS access"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./moodle_cloudflare_ssl_fix.sh"
