#!/bin/bash

# COMPREHENSIVE MOODLE FIX SOLUTION
# Complete solution for moodle.simondatalab.de issues

echo "🎓 COMPREHENSIVE MOODLE FIX SOLUTION"
echo "===================================="
echo ""
echo "Target: moodle.simondatalab.de"
echo "VM: 9001"
echo "Host: simonadmin@10.0.0.104"
echo ""

echo "🚨 CURRENT ISSUES IDENTIFIED:"
echo "============================="
echo "❌ VM 9001 is completely unreachable"
echo "❌ HTTP 526 error from Cloudflare"
echo "❌ SSL/TLS handshake failure"
echo ""

echo "🔍 ROOT CAUSE ANALYSIS:"
echo "======================="
echo "1. VM 9001 appears to be down or stopped"
echo "2. Cloudflare cannot connect to origin server"
echo "3. SSL certificate issues on origin server"
echo "4. Possible network configuration problems"
echo ""

echo "🛠️  COMPREHENSIVE FIX STRATEGY:"
echo "==============================="
echo ""

echo "PHASE 1: VM STATUS CHECK"
echo "------------------------"
echo "1. Check Proxmox dashboard for VM 9001 status"
echo "2. Verify VM is running and accessible"
echo "3. Check VM network configuration"
echo "4. Verify IP address assignment (10.0.0.104)"
echo ""

echo "PHASE 2: VM ACCESS AND DIAGNOSTICS"
echo "----------------------------------"
echo "1. Access VM via Proxmox console"
echo "2. Check system status and services"
echo "3. Verify Moodle installation"
echo "4. Check Apache and MySQL services"
echo ""

echo "PHASE 3: SERVICE RESTART AND CONFIGURATION"
echo "------------------------------------------"
echo "1. Restart Apache web server"
echo "2. Restart MySQL database"
echo "3. Restart Moodle services"
echo "4. Check Moodle configuration"
echo ""

echo "PHASE 4: SSL CERTIFICATE FIX"
echo "----------------------------"
echo "1. Check SSL certificate status"
echo "2. Generate new SSL certificate if needed"
echo "3. Configure Apache SSL virtual host"
echo "4. Test SSL connectivity"
echo ""

echo "PHASE 5: CLOUDFLARE CONFIGURATION"
echo "--------------------------------"
echo "1. Check Cloudflare SSL settings"
echo "2. Verify origin server certificate"
echo "3. Update SSL mode if needed"
echo "4. Test external connectivity"
echo ""

echo "🔧 DETAILED FIX COMMANDS:"
echo "========================"
echo ""

echo "VM Console Commands (via Proxmox):"
echo "----------------------------------"
echo "sudo systemctl status apache2"
echo "sudo systemctl status mysql"
echo "sudo systemctl status moodle"
echo "sudo systemctl restart apache2"
echo "sudo systemctl restart mysql"
echo "sudo systemctl restart moodle"
echo ""

echo "Moodle Configuration Check:"
echo "----------------------------"
echo "cd /var/www/html/moodle"
echo "cat config.php | grep -E 'dbhost|dbname|wwwroot'"
echo "php admin/cli/check_database_schema.php"
echo ""

echo "SSL Certificate Commands:"
echo "------------------------"
echo "sudo openssl x509 -in /etc/ssl/certs/ssl-cert-snakeoil.pem -text -noout"
echo "sudo a2enmod ssl"
echo "sudo a2enmod rewrite"
echo "sudo systemctl reload apache2"
echo ""

echo "Apache Configuration:"
echo "--------------------"
echo "sudo nano /etc/apache2/sites-available/moodle.conf"
echo "sudo a2ensite moodle"
echo "sudo systemctl reload apache2"
echo ""

echo "Log Checking:"
echo "------------"
echo "sudo tail -f /var/log/apache2/error.log"
echo "sudo tail -f /var/log/mysql/error.log"
echo "sudo journalctl -u apache2 -f"
echo ""

echo "🌐 CLOUDFLARE DASHBOARD SETTINGS:"
echo "================================"
echo ""
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Select: moodle.simondatalab.de"
echo "3. SSL/TLS > Overview:"
echo "   - Set SSL mode to 'Full' or 'Full (strict)'"
echo "4. SSL/TLS > Origin Server:"
echo "   - Check 'Origin Certificates'"
echo "   - Verify certificate is valid"
echo "5. DNS > Records:"
echo "   - Verify A record points to 10.0.0.104"
echo ""

echo "🧪 TESTING SEQUENCE:"
echo "==================="
echo ""
echo "1. Test VM connectivity:"
echo "   ping 10.0.0.104"
echo "   nc -z -v 10.0.0.104 80"
echo "   nc -z -v 10.0.0.104 443"
echo ""
echo "2. Test local VM services:"
echo "   curl -I http://localhost/"
echo "   curl -I https://localhost/"
echo ""
echo "3. Test external access:"
echo "   curl -I http://moodle.simondatalab.de/"
echo "   curl -I https://moodle.simondatalab.de/"
echo ""

echo "📋 STEP-BY-STEP ACTION PLAN:"
echo "============================"
echo ""
echo "STEP 1: Check VM Status"
echo "----------------------"
echo "1. Log into Proxmox dashboard"
echo "2. Navigate to VM 9001"
echo "3. Check if VM is running"
echo "4. If stopped, start the VM"
echo ""

echo "STEP 2: Access VM Console"
echo "------------------------"
echo "1. Click 'Console' in Proxmox"
echo "2. Login to VM (simonadmin)"
echo "3. Run diagnostic commands"
echo "4. Check service status"
echo ""

echo "STEP 3: Fix Services"
echo "-------------------"
echo "1. Restart Apache: sudo systemctl restart apache2"
echo "2. Restart MySQL: sudo systemctl restart mysql"
echo "3. Check Moodle: cd /var/www/html/moodle && php admin/cli/check_database_schema.php"
echo "4. Fix permissions: sudo chown -R www-data:www-data /var/www/html/moodle"
echo ""

echo "STEP 4: Fix SSL"
echo "--------------"
echo "1. Check SSL certificate: sudo openssl x509 -in /etc/ssl/certs/ssl-cert-snakeoil.pem -text -noout"
echo "2. Enable SSL modules: sudo a2enmod ssl && sudo a2enmod rewrite"
echo "3. Reload Apache: sudo systemctl reload apache2"
echo "4. Test SSL: curl -I https://localhost/"
echo ""

echo "STEP 5: Test External Access"
echo "---------------------------"
echo "1. Test HTTP: curl -I http://moodle.simondatalab.de/"
echo "2. Test HTTPS: curl -I https://moodle.simondatalab.de/"
echo "3. Check Cloudflare SSL settings if HTTPS fails"
echo "4. Verify DNS records"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "==================="
echo ""
echo "After successful fixes:"
echo "✅ VM 9001 is reachable via ping"
echo "✅ SSH access to VM works"
echo "✅ HTTP Status: 200 (instead of 526)"
echo "✅ HTTPS Status: 200 (instead of 526)"
echo "✅ Moodle login page loads correctly"
echo "✅ SSL certificate is valid"
echo "✅ Cloudflare can connect to origin server"
echo ""

echo "🚨 EMERGENCY CONTACTS:"
echo "====================="
echo ""
echo "If VM is completely inaccessible:"
echo "1. Check Proxmox host status"
echo "2. Check network infrastructure"
echo "3. Check VM backup status"
echo "4. Consider VM recovery procedures"
echo ""

echo "🔄 MONITORING COMMANDS:"
echo "====================="
echo ""
echo "Monitor VM status:"
echo "  watch -n 5 'ping -c 1 10.0.0.104'"
echo ""
echo "Monitor Moodle access:"
echo "  watch -n 10 'curl -s -o /dev/null -w \"%{http_code}\" https://moodle.simondatalab.de/'"
echo ""
echo "Monitor Apache logs:"
echo "  sudo tail -f /var/log/apache2/error.log"
echo ""

echo "📞 SUPPORT SUMMARY:"
echo "=================="
echo ""
echo "Current Status: VM 9001 unreachable"
echo "Primary Issue: VM appears to be down or stopped"
echo "Solution: Access via Proxmox console and restart services"
echo "Expected Fix Time: 15-30 minutes"
echo "Priority: High (Moodle is down)"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./moodle_comprehensive_fix.sh"
