#!/bin/bash

echo "🧭 Navigating to Live TV Settings in Jellyfin"
echo "==========================================="

echo "📍 You're currently in the Networking settings"
echo "We need to go to the Live TV settings instead"
echo ""
echo "📋 How to Navigate to Live TV Settings:"
echo "======================================"
echo ""
echo "1. 🔙 Go Back to Main Settings"
echo "   • Click the 'Back' button or 'Dashboard' in the top navigation"
echo "   • Or click on the Jellyfin logo to go to the home page"
echo ""
echo "2. 🏠 Go to Home Page"
echo "   • You should see the main Jellyfin dashboard"
echo "   • Look for the ⚙️ Settings gear icon in the top right corner"
echo ""
echo "3. ⚙️ Open Settings"
echo "   • Click the Settings gear icon (⚙️) in the top right"
echo "   • This will open the main settings menu"
echo ""
echo "4. 📺 Find Live TV"
echo "   • In the left sidebar, look for 'Live TV'"
echo "   • It should be in the main settings categories"
echo "   • Click on 'Live TV'"
echo ""
echo "5. ➕ Add Tuner"
echo "   • Once in Live TV settings, look for 'Add TV Provider' or 'Add Tuner'"
echo "   • Click that button to add a new M3U tuner"
echo ""
echo "📱 Alternative Navigation Path:"
echo "=============================="
echo "If you can't find the settings menu:"
echo "1. Look for a hamburger menu (☰) or three lines icon"
echo "2. Or try clicking on your username in the top right"
echo "3. Look for 'Settings' or 'Admin' options"
echo ""
echo "🎯 What You're Looking For:"
echo "=========================="
echo "• A page titled 'Live TV' or 'Live TV Configuration'"
echo "• Options to add 'Tuners' or 'TV Providers'"
echo "• M3U Tuner option"
echo "• Fields for Name, URL, User Agent, etc."
echo ""
echo "💡 Quick Tip:"
echo "============"
echo "If you're having trouble finding Live TV settings:"
echo "1. Make sure you're logged in as an administrator"
echo "2. Look for 'Dashboard' or 'Admin' in the navigation"
echo "3. Live TV might be under 'Media' or 'Content' settings"
echo ""
echo "🚀 Once you find Live TV settings:"
echo "================================="
echo "1. Click 'Add TV Provider' or 'Add Tuner'"
echo "2. Select 'M3U Tuner'"
echo "3. Use this URL: https://iptv-org.github.io/iptv/index.m3u"
echo "4. Set User Agent to: Jellyfin/10.10.7"
echo "5. Click Save"
echo ""
echo "📞 Need Help?"
echo "============"
echo "If you can't find the Live TV settings, try:"
echo "• Refreshing the page"
echo "• Logging out and back in"
echo "• Looking for 'Admin' or 'Dashboard' in the menu"

