#!/bin/bash

# COMPREHENSIVE VM 9001 FIX SOLUTION
# Complete solution for VM 9001 (moodle-lms-9001-1000104) issues

echo "🔧 COMPREHENSIVE VM 9001 FIX SOLUTION"
echo "====================================="
echo ""
echo "Target: VM 9001 (moodle-lms-9001-1000104)"
echo "User: simon@admin10.0.0.104"
echo "Services: Moodle (port 8086), Grafana (port 3000)"
echo ""

echo "🚨 CURRENT ISSUES IDENTIFIED:"
echo "============================="
echo "❌ VM 9001 is not accessible via SSH"
echo "❌ HTTP 526 errors from Cloudflare tunnel"
echo "❌ Moodle and Grafana services not responding"
echo "❌ VM may be down or stopped"
echo ""

echo "🔍 ROOT CAUSE ANALYSIS:"
echo "======================="
echo "1. VM 9001 appears to be down or stopped"
echo "2. SSH service not running or accessible"
echo "3. Cloudflare tunnel cannot connect to origin server"
echo "4. Services not running on expected ports"
echo ""

echo "🛠️  COMPREHENSIVE FIX STRATEGY:"
echo "==============================="
echo ""

echo "PHASE 1: VM STATUS CHECK"
echo "------------------------"
echo "1. Check Proxmox dashboard for VM 9001 status"
echo "2. Verify VM is running and accessible"
echo "3. Check VM network configuration"
echo "4. Verify IP address assignment (10.0.0.104)"
echo ""

echo "PHASE 2: VM ACCESS AND DIAGNOSTICS"
echo "----------------------------------"
echo "1. Access VM via Proxmox console"
echo "2. Check system status and services"
echo "3. Verify Moodle and Grafana installation"
echo "4. Check Apache/Nginx services"
echo ""

echo "PHASE 3: SERVICE RESTART AND CONFIGURATION"
echo "------------------------------------------"
echo "1. Restart Moodle service"
echo "2. Restart Grafana service"
echo "3. Restart Nginx/Apache web server"
echo "4. Check service configuration"
echo ""

echo "PHASE 4: NETWORK AND FIREWALL FIX"
echo "--------------------------------"
echo "1. Check NAT rules"
echo "2. Check firewall rules"
echo "3. Verify port forwarding"
echo "4. Test internal connectivity"
echo ""

echo "PHASE 5: CLOUDFLARE TUNNEL CONFIGURATION"
echo "---------------------------------------"
echo "1. Check Cloudflare SSL settings"
echo "2. Verify tunnel routes"
echo "3. Update SSL mode if needed"
echo "4. Test external connectivity"
echo ""

echo "🔧 DETAILED FIX COMMANDS:"
echo "========================"
echo ""

echo "VM Console Commands (via Proxmox):"
echo "----------------------------------"
echo "sudo systemctl status moodle"
echo "sudo systemctl status grafana"
echo "sudo systemctl status nginx"
echo "sudo systemctl restart moodle"
echo "sudo systemctl restart grafana"
echo "sudo systemctl restart nginx"
echo ""

echo "Network Configuration Check:"
echo "---------------------------"
echo "sudo iptables -t nat -L -n -v"
echo "sudo iptables -L -n -v"
echo "netstat -tlnp | grep -E ':(8086|3000|80|443)'"
echo ""

echo "Service Configuration Check:"
echo "---------------------------"
echo "sudo nginx -t"
echo "cat /etc/nginx/sites-available/moodle"
echo "cat /etc/nginx/sites-available/grafana"
echo ""

echo "Log Checking:"
echo "------------"
echo "sudo journalctl -u moodle -f"
echo "sudo journalctl -u grafana -f"
echo "sudo journalctl -u nginx -f"
echo ""

echo "🌐 CLOUDFLARE DASHBOARD SETTINGS:"
echo "================================"
echo ""
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Select: simondatalab.de"
echo "3. SSL/TLS > Overview:"
echo "   - Set SSL mode to 'Flexible' (for tunnel routes)"
echo "4. Check tunnel configuration:"
echo "   - moodle.simondatalab.de → http://10.0.0.104:8086"
echo "   - grafana.simondatalab.de → http://10.0.0.104:3000"
echo ""

echo "🧪 TESTING SEQUENCE:"
echo "==================="
echo ""
echo "1. Test VM connectivity:"
echo "   ping 10.0.0.104"
echo "   nc -z -v 10.0.0.104 8086"
echo "   nc -z -v 10.0.0.104 3000"
echo ""
echo "2. Test local VM services:"
echo "   curl -I http://localhost:8086/"
echo "   curl -I http://localhost:3000/"
echo ""
echo "3. Test external access:"
echo "   curl -I https://moodle.simondatalab.de/"
echo "   curl -I https://grafana.simondatalab.de/"
echo ""

echo "📋 STEP-BY-STEP ACTION PLAN:"
echo "============================"
echo ""
echo "STEP 1: Check VM Status"
echo "----------------------"
echo "1. Log into Proxmox dashboard"
echo "2. Navigate to VM 9001"
echo "3. Check if VM is running"
echo "4. If stopped, start the VM"
echo ""

echo "STEP 2: Access VM Console"
echo "------------------------"
echo "1. Click 'Console' in Proxmox"
echo "2. Login to VM (simon)"
echo "3. Run diagnostic commands"
echo "4. Check service status"
echo ""

echo "STEP 3: Fix Services"
echo "-------------------"
echo "1. Restart Moodle: sudo systemctl restart moodle"
echo "2. Restart Grafana: sudo systemctl restart grafana"
echo "3. Restart Nginx: sudo systemctl restart nginx"
echo "4. Check status: systemctl is-active moodle grafana nginx"
echo ""

echo "STEP 4: Fix Network"
echo "------------------"
echo "1. Check NAT rules: sudo iptables -t nat -L -n -v"
echo "2. Check firewall: sudo iptables -L -n -v"
echo "3. Check ports: netstat -tlnp | grep -E ':(8086|3000)'"
echo "4. Test local: curl -I http://localhost:8086/"
echo ""

echo "STEP 5: Test External Access"
echo "---------------------------"
echo "1. Test HTTP: curl -I https://moodle.simondatalab.de/"
echo "2. Test HTTP: curl -I https://grafana.simondatalab.de/"
echo "3. Check Cloudflare SSL settings if HTTPS fails"
echo "4. Verify tunnel configuration"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "=================="
echo ""
echo "After successful fixes:"
echo "✅ VM 9001 is reachable via ping"
echo "✅ SSH access to VM works"
echo "✅ Moodle service running on port 8086"
echo "✅ Grafana service running on port 3000"
echo "✅ HTTP Status: 200 (instead of 526)"
echo "✅ Services accessible via HTTPS"
echo "✅ Cloudflare tunnel working correctly"
echo ""

echo "🚨 EMERGENCY CONTACTS:"
echo "====================="
echo ""
echo "If VM is completely inaccessible:"
echo "1. Check Proxmox host status"
echo "2. Check network infrastructure"
echo "3. Check VM backup status"
echo "4. Consider VM recovery procedures"
echo ""

echo "🔄 MONITORING COMMANDS:"
echo "====================="
echo ""
echo "Monitor VM status:"
echo "  watch -n 5 'ping -c 1 10.0.0.104'"
echo ""
echo "Monitor service access:"
echo "  watch -n 10 'curl -s -o /dev/null -w \"%{http_code}\" https://moodle.simondatalab.de/'"
echo ""
echo "Monitor service logs:"
echo "  sudo journalctl -u moodle -f"
echo ""

echo "📞 SUPPORT SUMMARY:"
echo "=================="
echo ""
echo "Current Status: VM 9001 not accessible"
echo "Primary Issue: VM appears to be down or stopped"
echo "Solution: Access via Proxmox console and restart services"
echo "Expected Fix Time: 15-30 minutes"
echo "Priority: High (Moodle and Grafana are down)"
echo ""
echo "🔄 To run this diagnostic again:"
echo "  ./vm_9001_comprehensive_fix.sh"
