#!/bin/bash

# VM 9001 DOCKER CONTAINER DIAGNOSTIC SCRIPT
# Based on the Proxmox console output showing running containers

echo "🐳 VM 9001 DOCKER CONTAINER DIAGNOSTIC"
echo "======================================"
echo ""
echo "Target: VM 9001 (moodle-lms-9001-1000104)"
echo "User: simonadmin@pythonacademy"
echo "Status: VM is running with Docker containers"
echo ""

echo "🔍 CONTAINER STATUS ANALYSIS:"
echo "============================="
echo ""
echo "✅ Grafana: Running on port 3000"
echo "✅ Moodle: Running on port 8086"
echo "✅ PostgreSQL: Running for Moodle"
echo "✅ Prometheus Stack: All monitoring services up"
echo ""

echo "🚨 ISSUE IDENTIFICATION:"
echo "========================"
echo ""
echo "The containers are running, but external access is failing."
echo "This suggests a network/firewall configuration issue."
echo ""

echo "🔧 DOCKER CONTAINER COMMANDS TO RUN:"
echo "==================================="
echo ""

echo "1. Check container logs:"
echo "------------------------"
echo "docker logs grafana"
echo "docker logs moodle-databricks-fresh"
echo "docker logs moodle-postgres"
echo ""

echo "2. Check container network:"
echo "--------------------------"
echo "docker network ls"
echo "docker inspect grafana"
echo "docker inspect moodle-databricks-fresh"
echo ""

echo "3. Test internal connectivity:"
echo "-----------------------------"
echo "curl -I http://localhost:3000/"
echo "curl -I http://localhost:8086/"
echo ""

echo "4. Check port bindings:"
echo "----------------------"
echo "docker port grafana"
echo "docker port moodle-databricks-fresh"
echo ""

echo "5. Check container health:"
echo "-------------------------"
echo "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"
echo ""

echo "🌐 NETWORK DIAGNOSTIC COMMANDS:"
echo "==============================="
echo ""

echo "1. Check listening ports:"
echo "------------------------"
echo "netstat -tlnp | grep -E ':(3000|8086|8080)'"
echo ""

echo "2. Check firewall rules:"
echo "----------------------"
echo "sudo iptables -L -n -v"
echo "sudo iptables -t nat -L -n -v"
echo ""

echo "3. Check Docker networks:"
echo "------------------------"
echo "docker network inspect bridge"
echo ""

echo "4. Test external connectivity:"
echo "-----------------------------"
echo "curl -I http://10.0.0.104:3000/"
echo "curl -I http://10.0.0.104:8086/"
echo ""

echo "🛠️  FIX COMMANDS:"
echo "==============="
echo ""

echo "1. Restart containers if needed:"
echo "-------------------------------"
echo "docker restart grafana"
echo "docker restart moodle-databricks-fresh"
echo ""

echo "2. Check container resource usage:"
echo "---------------------------------"
echo "docker stats --no-stream"
echo ""

echo "3. Verify container configuration:"
echo "--------------------------------"
echo "docker inspect grafana | grep -A 10 'PortBindings'"
echo "docker inspect moodle-databricks-fresh | grep -A 10 'PortBindings'"
echo ""

echo "🧪 TESTING SEQUENCE:"
echo "==================="
echo ""

echo "1. Test local container access:"
echo "------------------------------"
echo "curl -I http://localhost:3000/"
echo "curl -I http://localhost:8086/"
echo ""

echo "2. Test external access:"
echo "----------------------"
echo "curl -I https://moodle.simondatalab.de/"
echo "curl -I https://grafana.simondatalab.de/"
echo ""

echo "3. Check Cloudflare tunnel status:"
echo "--------------------------------"
echo "Check if tunnel is running and configured correctly"
echo ""

echo "📋 IMMEDIATE ACTION PLAN:"
echo "========================"
echo ""

echo "STEP 1: Check Container Logs"
echo "--------------------------"
echo "Run: docker logs grafana"
echo "Run: docker logs moodle-databricks-fresh"
echo "Look for any error messages or connection issues"
echo ""

echo "STEP 2: Test Internal Connectivity"
echo "--------------------------------"
echo "Run: curl -I http://localhost:3000/"
echo "Run: curl -I http://localhost:8086/"
echo "Verify containers respond internally"
echo ""

echo "STEP 3: Check Network Configuration"
echo "----------------------------------"
echo "Run: netstat -tlnp | grep -E ':(3000|8086)'"
echo "Verify ports are properly bound"
echo ""

echo "STEP 4: Test External Access"
echo "---------------------------"
echo "Run: curl -I https://moodle.simondatalab.de/"
echo "Run: curl -I https://grafana.simondatalab.de/"
echo "Check if Cloudflare tunnel is working"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "=================="
echo ""
echo "After running these commands:"
echo "✅ Container logs show no errors"
echo "✅ Internal curl tests return HTTP 200"
echo "✅ External curl tests return HTTP 200"
echo "✅ Ports are properly bound"
echo "✅ Cloudflare tunnel is working"
echo ""

echo "🚨 TROUBLESHOOTING NOTES:"
echo "========================"
echo ""
echo "If containers are running but external access fails:"
echo "1. Check Cloudflare tunnel configuration"
echo "2. Verify SSL settings in Cloudflare dashboard"
echo "3. Check if tunnel is running on the host"
echo "4. Verify NAT rules for port forwarding"
echo ""

echo "🔄 To run this diagnostic again:"
echo "  ./vm_9001_docker_diagnostic.sh"
