#!/bin/bash

# VM 9001 MLFLOW REMOVAL - PROXMOX CONSOLE COMMANDS
# Run these commands directly in the Proxmox console

echo "🐳 VM 9001 MLFLOW REMOVAL - PROXMOX CONSOLE COMMANDS"
echo "==================================================="
echo ""
echo "Run these commands in the Proxmox console for VM 9001:"
echo ""

echo "1. CHECK CURRENT CONTAINERS:"
echo "============================"
echo "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"
echo ""

echo "2. FIND MLFLOW CONTAINERS:"
echo "========================="
echo "docker ps | grep -i mlflow"
echo "docker ps -a | grep -i mlflow"
echo ""

echo "3. STOP MLFLOW CONTAINERS:"
echo "========================="
echo "docker stop \$(docker ps -q --filter 'name=mlflow') 2>/dev/null || echo 'No MLflow containers to stop'"
echo ""

echo "4. REMOVE MLFLOW CONTAINERS:"
echo "==========================="
echo "docker rm \$(docker ps -aq --filter 'name=mlflow') 2>/dev/null || echo 'No MLflow containers to remove'"
echo ""

echo "5. REMOVE MLFLOW IMAGES:"
echo "======================="
echo "docker images | grep -i mlflow"
echo "docker rmi \$(docker images -q --filter 'reference=*mlflow*') 2>/dev/null || echo 'No MLflow images to remove'"
echo ""

echo "6. REMOVE MLFLOW VOLUMES:"
echo "========================"
echo "docker volume ls | grep -i mlflow"
echo "docker volume rm \$(docker volume ls -q --filter 'name=mlflow') 2>/dev/null || echo 'No MLflow volumes to remove'"
echo ""

echo "7. REMOVE MLFLOW NETWORKS:"
echo "========================="
echo "docker network ls | grep -i mlflow"
echo "docker network rm \$(docker network ls -q --filter 'name=mlflow') 2>/dev/null || echo 'No MLflow networks to remove'"
echo ""

echo "8. CLEAN UP DOCKER SYSTEM:"
echo "========================"
echo "docker system prune -f"
echo ""

echo "9. VERIFY REMAINING SERVICES:"
echo "==========================="
echo "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"
echo ""

echo "10. TEST REMAINING SERVICES:"
echo "==========================="
echo "curl -I http://localhost:3000/"
echo "curl -I http://localhost:8086/"
echo ""

echo "🌐 CLOUDFLARE TUNNEL UPDATE:"
echo "==========================="
echo ""
echo "After removing MLflow, update Cloudflare tunnel routes:"
echo "1. Remove: mlflow.simondatalab.de → http://10.0.0.104:5000"
echo "2. Keep: moodle.simondatalab.de → http://10.0.0.104:8086"
echo "3. Keep: grafana.simondatalab.de → http://10.0.0.104:3000"
echo ""

echo "📋 QUICK REMOVAL SEQUENCE:"
echo "========================="
echo ""
echo "Run these commands in order:"
echo "1. docker ps | grep -i mlflow"
echo "2. docker stop \$(docker ps -q --filter 'name=mlflow')"
echo "3. docker rm \$(docker ps -aq --filter 'name=mlflow')"
echo "4. docker rmi \$(docker images -q --filter 'reference=*mlflow*')"
echo "5. docker volume rm \$(docker volume ls -q --filter 'name=mlflow')"
echo "6. docker network rm \$(docker network ls -q --filter 'name=mlflow')"
echo "7. docker system prune -f"
echo "8. docker ps"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "=================="
echo ""
echo "After running these commands:"
echo "✅ MLflow containers: Removed"
echo "✅ MLflow images: Removed"
echo "✅ MLflow volumes: Removed"
echo "✅ MLflow networks: Removed"
echo "✅ Remaining services: Grafana, Moodle, PostgreSQL, Prometheus"
echo "✅ Port 5000: Available for other services"
echo ""

echo "🚨 IMPORTANT NOTES:"
echo "=================="
echo ""
echo "1. MLflow data will be permanently deleted"
echo "2. Any MLflow experiments/models will be lost"
echo "3. Update Cloudflare tunnel configuration"
echo "4. Update any monitoring/alerting for MLflow"
echo "5. Consider backing up MLflow data if needed"
echo ""

echo "🔄 Run these commands in the Proxmox console now!"
