#!/bin/bash

# VM 9001 IMMEDIATE DIAGNOSTIC COMMANDS
# Run these commands in the Proxmox console

echo "🔧 VM 9001 IMMEDIATE DIAGNOSTIC COMMANDS"
echo "======================================="
echo ""
echo "Run these commands in the Proxmox console:"
echo ""

echo "1. CHECK CONTAINER LOGS:"
echo "======================="
echo "docker logs grafana"
echo "docker logs moodle-databricks-fresh"
echo ""

echo "2. TEST INTERNAL CONNECTIVITY:"
echo "============================="
echo "curl -I http://localhost:3000/"
echo "curl -I http://localhost:8086/"
echo ""

echo "3. CHECK PORT BINDINGS:"
echo "======================"
echo "netstat -tlnp | grep -E ':(3000|8086)'"
echo "docker port grafana"
echo "docker port moodle-databricks-fresh"
echo ""

echo "4. CHECK FIREWALL RULES:"
echo "======================="
echo "sudo iptables -L -n -v"
echo "sudo iptables -t nat -L -n -v"
echo ""

echo "5. TEST EXTERNAL CONNECTIVITY:"
echo "============================="
echo "curl -I http://10.0.0.104:3000/"
echo "curl -I http://10.0.0.104:8086/"
echo ""

echo "6. CHECK DOCKER NETWORKS:"
echo "========================"
echo "docker network ls"
echo "docker network inspect bridge"
echo ""

echo "7. RESTART CONTAINERS IF NEEDED:"
echo "==============================="
echo "docker restart grafana"
echo "docker restart moodle-databricks-fresh"
echo ""

echo "8. VERIFY CONTAINER STATUS:"
echo "=========================="
echo "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"
echo ""

echo "🌐 CLOUDFLARE TUNNEL CHECK:"
echo "==========================="
echo ""
echo "If containers are working internally but external access fails:"
echo "1. Check if Cloudflare tunnel is running"
echo "2. Verify tunnel configuration"
echo "3. Check SSL settings in Cloudflare dashboard"
echo ""

echo "📋 QUICK FIX SEQUENCE:"
echo "====================="
echo ""
echo "1. Run: docker logs grafana"
echo "2. Run: curl -I http://localhost:3000/"
echo "3. Run: curl -I http://localhost:8086/"
echo "4. Run: netstat -tlnp | grep -E ':(3000|8086)'"
echo "5. Run: curl -I https://moodle.simondatalab.de/"
echo "6. Run: curl -I https://grafana.simondatalab.de/"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "=================="
echo ""
echo "✅ Grafana logs: No errors"
echo "✅ Moodle logs: No errors"
echo "✅ Internal curl: HTTP 200"
echo "✅ Ports: Properly bound"
echo "✅ External curl: HTTP 200"
echo ""

echo "🚨 IF EXTERNAL ACCESS STILL FAILS:"
echo "================================="
echo ""
echo "The issue is likely Cloudflare tunnel configuration:"
echo "1. Check Cloudflare dashboard SSL settings"
echo "2. Verify tunnel is running on host"
echo "3. Check tunnel routes configuration"
echo "4. Set SSL mode to 'Flexible' if needed"
echo ""

echo "🔄 Run these commands in the Proxmox console now!"
