#!/bin/bash
# Setup Moodle for Automated Deployment
# This script guides you through enabling web services and creating a token

echo "========================================================================"
echo "  MOODLE WEB SERVICES SETUP"
echo "========================================================================"
echo ""
echo "This script will help you set up Moodle for automated deployment."
echo ""

MOODLE_URL="https://moodle.simondatalab.de"
TOKEN_FILE="$HOME/.moodle_token"

echo "Step 1: Enable Web Services in Moodle"
echo "----------------------------------------"
echo "1. Go to: $MOODLE_URL/admin/search.php?query=enablewebservices"
echo "2. Enable 'Enable web services'"
echo "3. Click 'Save changes'"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 2: Enable REST Protocol"
echo "----------------------------------------"
echo "1. Go to: $MOODLE_URL/admin/settings.php?section=webserviceprotocols"
echo "2. Enable 'REST protocol'"
echo "3. Click 'Save changes'"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 3: Create a Web Service"
echo "----------------------------------------"
echo "1. Go to: $MOODLE_URL/admin/settings.php?section=externalservices"
echo "2. Click 'Add' under 'External services'"
echo "3. Name: 'Vietnamese Course Deployment'"
echo "4. Short name: 'vietnamese_deployment'"
echo "5. Enabled: Yes"
echo "6. Authorized users only: Yes"
echo "7. Click 'Add service'"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 4: Add Functions to Web Service"
echo "----------------------------------------"
echo "1. Click 'Add functions' next to your new service"
echo "2. Add these functions (search and add one by one):"
echo ""
echo "   Core functions:"
echo "   - core_course_get_contents"
echo "   - core_course_get_courses"
echo "   - core_question_get_categories"
echo "   - core_question_import_questions"
echo "   - core_question_create_categories"
echo ""
echo "   Module functions:"
echo "   - mod_page_add_page"
echo "   - mod_assign_create_assignments"
echo "   - mod_resource_add_resource"
echo ""
echo "3. Click 'Add functions' for each"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 5: Authorize User"
echo "----------------------------------------"
echo "1. Click 'Authorised users' next to your service"
echo "2. Select your admin user"
echo "3. Click 'Add'"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 6: Create Token"
echo "----------------------------------------"
echo "1. Go to: $MOODLE_URL/admin/settings.php?section=webservicetokens"
echo "2. Under 'Create token', select:"
echo "   - User: Your admin account"
echo "   - Service: Vietnamese Course Deployment"
echo "3. Click 'Save changes'"
echo "4. Copy the generated token"
echo ""
echo -n "Paste your token here: "
read -s MOODLE_TOKEN
echo ""

if [ -n "$MOODLE_TOKEN" ]; then
    echo "$MOODLE_TOKEN" > "$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
    echo ""
    echo "✓ Token saved to: $TOKEN_FILE"
else
    echo ""
    echo "⚠️  No token provided. You can save it manually to: $TOKEN_FILE"
fi

echo ""
echo "========================================================================"
echo "  SETUP COMPLETE!"
echo "========================================================================"
echo ""
echo "You can now run automated deployments:"
echo ""
echo "  # Deploy everything"
echo "  python3 moodle_deployer.py --deploy-all"
echo ""
echo "  # Deploy specific components"
echo "  python3 moodle_deployer.py --deploy-quizzes"
echo "  python3 moodle_deployer.py --deploy-lessons"
echo "  python3 moodle_deployer.py --deploy-resources"
echo "  python3 moodle_deployer.py --deploy-assignments"
echo ""
