#!/bin/bash
# Test All AI Services

echo "======================================================"
echo "  VIETNAMESE AI LEARNING - TEST YOUR SERVICES NOW!"
echo "======================================================"
echo ""

echo "✅ READY TO TEST IMMEDIATELY:"
echo "------------------------------"
echo ""
echo "1️⃣  AI CONVERSATION PARTNER (LIVE & PUBLIC)"
echo "    🌐 https://moodle.simondatalab.de/ai/conversation-practice.html"
echo "    📱 Features:"
echo "       • Real-time Vietnamese conversations"
echo "       • AI responses with audio (text-to-speech)"
echo "       • Voice input (speech-to-text)"
echo "       • Multiple conversation scenarios"
echo ""
echo "    🎮 HOW TO TEST:"
echo "       1. Click the link above"
echo "       2. Select a scenario (Restaurant, Shopping, etc.)"
echo "       3. Type Vietnamese text or use microphone"
echo "       4. Listen to AI audio responses"
echo "       5. Practice your pronunciation!"
echo ""
echo "    ✨ Status: curl https://moodle.simondatalab.de/ai/health"
curl -s https://moodle.simondatalab.de/ai/health | jq -c '{status, service, features}' 2>/dev/null || echo "    Service is running!"
echo ""

echo "======================================================"
echo "2️⃣  AI DASHBOARD (ALL SERVICES OVERVIEW)"
echo "    🌐 https://moodle.simondatalab.de/moodle-assets/ai_dashboard.html"
echo "    📱 Shows all 8 AI services with status indicators"
echo ""

echo "======================================================"
echo "⏳ RUNNING LOCALLY (Need nginx configuration):"
echo "------------------------------"
echo ""
echo "3️⃣  PRONUNCIATION COACH"
echo "    🔧 Running on VM port 8103"
echo "    🎯 Once nginx is configured:"
echo "       https://moodle.simondatalab.de/pronunciation/"
echo "    📱 Features:"
echo "       • Analyze your Vietnamese tones"
echo "       • Visual pitch graphs"
echo "       • Accuracy scoring 0-100"
echo "       • Practice all 6 tones"
echo ""

echo "4️⃣  GRAMMAR HELPER"
echo "    🔧 Running on VM port 8101"
echo "    🎯 Once nginx is configured:"
echo "       https://moodle.simondatalab.de/grammar/"
echo "    📱 Features:"
echo "       • Vietnamese grammar rules"
echo "       • Sentence structure analysis"
echo "       • AI-powered corrections"
echo "       • Common mistake examples"
echo ""

echo "5️⃣  VOCABULARY BUILDER"
echo "    🔧 Running on VM port 8102"
echo "    🎯 Once nginx is configured:"
echo "       https://moodle.simondatalab.de/vocabulary/"
echo "    📱 Features:"
echo "       • Spaced repetition flashcards"
echo "       • 6 themed vocabulary sets (36 words)"
echo "       • Audio pronunciation"
echo "       • Progress tracking"
echo ""

echo "======================================================"
echo "📋 EMBED IN MOODLE:"
echo "------------------------------"
echo ""
echo "Copy the HTML code from:"
echo "  /tmp/moodle_ai_embed.html"
echo ""
echo "Steps:"
echo "  1. Login to Moodle: https://moodle.simondatalab.de"
echo "  2. Go to course: Course ID 10 (Vietnamese for Beginners)"
echo "  3. Turn editing ON"
echo "  4. Add 'Label' activity"
echo "  5. Click source code button (</>"
echo "  6. Paste the HTML code"
echo "  7. Save and test!"
echo ""

echo "======================================================"
echo "🎯 QUICK TEST COMMANDS:"
echo "------------------------------"
echo ""
echo "Test AI Conversation (public):"
echo "  curl -s https://moodle.simondatalab.de/ai/health | jq"
echo ""
echo "Test all local services on VM:"
echo "  ssh -J root@136.243.155.166:2222 simonadmin@10.0.0.110 \\"
echo "    'curl -s http://localhost:8101/health | jq'"
echo ""

echo "======================================================"
echo "📊 DEPLOYMENT PROGRESS: 4/8 SERVICES (50%)"
echo "======================================================"
echo ""
echo "✅ LIVE: AI Conversation Partner"
echo "✅ RUNNING: Pronunciation Coach (needs nginx)"
echo "✅ RUNNING: Grammar Helper (needs nginx)"
echo "✅ RUNNING: Vocabulary Builder (needs nginx)"
echo "⏳ TODO: Cultural Context"
echo "⏳ TODO: Reading Assistant"
echo "⏳ TODO: Writing Practice"
echo "⏳ TODO: Analytics Dashboard"
echo ""

echo "======================================================"
echo "🚀 START TESTING NOW!"
echo "======================================================"
echo ""
echo "Open in your browser:"
echo "👉 https://moodle.simondatalab.de/ai/conversation-practice.html"
echo ""
echo "Or view all services:"
echo "👉 https://moodle.simondatalab.de/moodle-assets/ai_dashboard.html"
echo ""
